### ISSUE TITLE
JEM 2.1.5: import problem!

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1001]
Hi, there seems to be an import problem (from csv)
There is in forum a topic about importing from Joomla 2.5.28
I tried with exporting from 3.4.5 one site to another:
there is only one event, one category, no venue imported!

I am logged in as superuser

it seems I can reproduce this error!

**Comment by JKoelman** [comment]
did try it out too (3.4.5 export, then removed entry's by using the cleanup button, and then imported the files.....and replace id if exist) but can't replicate the issue for now.

**Comment by jojo12** [comment]
I retried, as you now with "replace if ID exist", now all are integrated.
Now my question is: when the other  setting makes sense?
(normally I always used "replace if ID exist", now the first time not and there I had the problem.
Can someone explain me?

**Comment by jojo12** [comment]
"Replace if ID exists (else create new).: no"
what is this option for?

with this "yes" I can import all to a new JEM.

with this "no" there seems to be problem to import all to a new JEM

perhaps I don't understand it and have to translate the explanation better.

**Comment by JKoelman** [comment]
> Replace if ID exists (else create new).: no"
what is this option for?

it's referring to the id field of the table. With the id you can indentify the row.

When having the option to "no" i think it's hiding the id field upon import so it will be a "save" action and data will be added to new rows with new id's.  With the option switched on it will be "replace" action as it will add the id field upon import.   And the id part is important as it will link categories/venues/events etc...

but maybe i'm wrong

**Comment by jojo12** [comment]
can you test please:
import with no events, categories, venues and catevents with the setting to "replace if ID exists (else create new):: no"
when there are no events, categories, venues and catevents, there exist no IDs, so JEM will create new ones. But then I think all the events, venues, categories and catevents should be imported too!

Or am I wrong?

**Comment by JKoelman** [comment]
uhm, there seems to be something wrong with the option set to "no". Had 3 venues in the database and tried to import a file with +/- 600.  The message that appeared was stating that it did import the venues but in fact it did import just 1.   With replace id to yes it was importing all the venues.

**Comment by JKoelman** [comment]
so wouold say something is wrong but maybe i'm also not sure how it should be working.

**Comment by JKoelman** [comment]
tried out again:  

cleaned the db and tried only to import the venues.csv with +/- 600 venues.
Option set to no and result: only 1 was imported

**Comment by JKoelman** [comment]
did change the function import in the model and replaced the ```$object->bind($object,$ignore)``` to

```if (!$replace){$values['id'] = 0;} $object->bind($values);``` and seems to be importing. Guess the bind function wants to have an id and by passing a 0 it will indetify it as a new row.  But maybe i'm wrong there.

**Comment by jojo12** [comment]
I tried with replace=no, this is importing fine now.
but then I tried with importing the same with replace=yes, all events are now doubled.
In my thinking, they should be replaced/updated not added

**Comment by Hoffi1** [comment]
I have not looked at the problem itself until now but some words to the questions:
- replace=no is very dangerous in my eyes because tables are imported one by one. So there is no way to map e.g. category ids from these listed in event.csv to the new in db after importing category.csv. Changing IDs require to also change all references.
- If your first import with "replace=no" used higher IDs (because table's next id to use was set such high caused by a previous try) you get doubled entries. That's because the ID is the key.

**Comment by Hoffi1** [comment]
@JKoelman: Your change shouldn't make a difference. In original code some lines above ```$ignore``` gets 'id' so ```bind()``` will bind all fields of ```$values``` except ['id'].

I shortly tried with exporting one event and importing it back with replace=no. It added a new event as expected. Seems I must debug deeper...

**Comment by JKoelman** [comment]
think it will be more clear when testing with more then 1.
This as 1 is not a problem :)

**Comment by Hoffi1** [comment]
You're right. How could I idiot think ```reset()``` would reset all fields... :angry: 
will provide a fix with Hoffi-touch. :wink:

**Comment by jojo12** [comment]
not yet fixed!
I imported now with the new model in a clean db the exported csv files. In order of venues, categories, events, catevents. then I used in categories the "wiederherstellen" button.
All is imported but not the links between events and categories, So I don't see any event in simplelist.

Then I imported the same once again but with replace=yes. 
all is now good linked between events and categories, I see all the events in simplelist. But:
al is doubled!
In my mind this should update the existing raws (=overwrite with the new), and only if the ID doesn't exist create a new raw with a new ID.

**Comment by Hoffi1** [comment]
This is by design and can't be fixed except by deleting and completely new developing Export/Import.
(a) If a user imports categories or venues with replace=no it's nearly guaranteed that importing events will not work as expected because the IDs have changed undocumented.
(b) If two items have different IDs they are different. We humans may call them doubled but for the software/database they are not the same. There is no safe way to identify items with different IDs as identical.

The original problem of importing all items with identical ID (which results in only one event/category/venue) is fixed. You can now import categories or venues with replace=no and get them all. But you have to manually patch the event.csv before importing events.
To automate this all data must be exported/imported at once so the code can map the IDs. That's a big enhancement task we should track separately if we decide to implement this.

btw: If we add ACL on category/event/venue level we will get additional trouble with assets table. We could additionally export data from there but then we get trouble with access levels, user groups, users, ... - all things are connected together using their IDs. But these IDs are only unique inside a single website.
