### ISSUE TITLE
FR: not attending

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1036]
(I am loud thinking about our old problem:)

if we could split:
"the user said something about his attending" -> yes /no
and after:
the user is attending / the user is not attending (the user can switch -but he always said something)
?

**Comment by Hoffi1** [comment]
The main problem is that every entry in the attendee table is counted. So if we store non-attendees too we must walk through all the code and exclude such entries from "normal" handling. Maybe there are not much pieces in code. But the big task is to find them _all_, also in all modules, plugins, 3rd party.

**Comment by jojo12** [comment]
[Once more loud thinking]
There are 2 different things:
One thing is: registering/unregistering for an event (unregistering only when registered)
->this is counting.

The other thing is: communicating to non attend an event. 
-> this needs no counting (or only a separated counting)

So the start in eventview (frontend) could be: the title "Anmeldung/Abmeldung" (it's easier to say in german)
after to decide, if user wants to register for an event (or if he is just registered to unregister)
or if he wants to say, he will not attend.

I think in the component, this could be with only an additional file which shows the user which are not attending the event.

**Comment by jojo12** [comment]
you said, every entry is counted, but there are entries for the waitinglist (with 1).
Is it not possible to have non-attendings e.g. with -1
so the count is: "this user said something about registering or non attending.

**Comment by Hoffi1** [comment]
Sure, -1 would be an acceptable way (ignoring the then non-perfect name "waiting" for that table field :wink: ).

But it doesn't help to solve the main issue: Instead of only (potential) attendees we have now also absolute non-attendees stored which must be filtered out everywhere. And this "maywhere" is the big task. Especially the independent updateable CB plugin which would show these users as "on waiting list" (because "waiting" is not zero). Because currently "waiting" can have only two values the checks are implemented as "0 OR all other values" or "1 OR all other values" but not "0 OR 1 OR whatever else". So in some cases such entries will be handled as "registered", the other cases as "on waiting list".

**Comment by jojo12** [comment]
Perhaps the first idea is better: to add a nearly parallel table e.g. #_jem_nonattend.

**Comment by jojo12** [comment]
someday, I'll succeed!

**Comment by Hoffi1** [comment]
???

Hm...I think I prefer one table, maybe with additional fields. Releasing 3rd party plugins "understanding" the new states before releasing a JEM using these states should be an acceptable way, I think.

If I remember right you would like to "pre-define" potential attendees when creating an event? So we would have an additional state "invited". Then we can add users invited to attendees table before they answer. I'm also thinking about inviting complete user group(s) - maybe this will become too complicated in detail (because they are dynamically), not sure.

If we also allow users to say "yes", "no", "don't know but have comment" I see a conflict with waiting list. So currently I think a dedicated state field should be the best solution. So movements between attendee and waiting list will not influence user's answer (assuming "don't know" will be handled like "yes" and user will get a reservation if waiting list feature is activated).

Summary:
I would like to enhance attendees table by fields "state" and "comment" with states -1: No, 0: invited, 1: Yes, 2: Don't know/maybe. So the queries just need a "WHERE state > 0" clause to get the same functionality as currrently. For full support all states must be respected(e.g. by showing corresponding icons).

**Comment by Hoffi1** [comment]
more detailed roadmap:
- JEM 2.1.6: add fields "state" and "comment" to attendees table, always set state to 1 if user clicks "I will attend" which creates the record.
- plugins: add at least "WHERE state > 0" clause or fully implement handling of all states
- JEM 2.1.7 / 3.1.x: add full feature. (as full as time allows :wink: maybe without invitation part first)

**Comment by jojo12** [comment]
no, me, I don't need predefined attendees (because I am administrator and eventcreator), all users of my site are potential attendees.
I make a difference between registered users (for an event). They reserved a place for an event (and have perhaps to pay for this place). If there is a reason they can not use this reserved place (it could be possible, they can unregister (that means cancel). This part works best!

A totally other thing is, when a user wants to say, he will be absent. So no place is reserved for him.
If something changes, then at first he can delete his notification of absence. But this is not yet the reserving/registering of a place (he has e.g. to pay for).

a user said something about an event      ---> registering for a place     ---> waitinglist
                                                                        --->unregistering=giving free this place

                                                                ---> notification of absence
                                                                       --> deleting this notification.

**Comment by jojo12** [comment]
I would never reserve a ticket for a user who says, I don't know.

**Comment by Hoffi1** [comment]
New CB plugins (v2.1.6) will be able to handle planned registration enhancements. They work together with old or new JEM. So the only dependency is: if using enhanced registration features with a future JEM the CB plugins must be at least v2.1.6 (or special 2.1.4.1 for CB 1.9 users :wink: ).

Because JEM itself hasn't implemented this feature yet the only way to test is by manually patching the db table. Please note that for status 0 (invited) a new icon is used which will be installed by com_jem v2.1.6 (dev5 or later).

Planned values for 'status' field:
1: user registered / accepted to buy the ticket / ... as now
-1: user explicitely unregistered / says (s)he will not attend / not buy anything / ...
0: event owner invited this user, user has not answered yet

**Comment by jojo12** [comment]
I just tried and will wait for this feature in jem ;-) . it's very interesting.

[welcome back!]

**Comment by jojo12** [comment]
so if I understand right:
when registering for an event, there's a new raw in jem_register with 
no reaction                                              -> no entry in jem_register
registered for event:                                -> status=1 and waitinglist=0 (unregistering: deleting entry)?
registered for event, but on waitinglist     -> status=1 and waitinglist=1 (unregistering: waitinglist=0)
invited from owner, but no reaction          -> status=0 and waitinglist=0 ?
reaction saying no                                   -> status=-1 and waitinglist=0 ?

**Comment by jojo12** [comment]
in cb_jemattending: there are the symbols:
I have on with yes 
one with ?
one with x
im cb_jemevents: there are only numbers, I don't understand:

![registerd](https://cloud.githubusercontent.com/assets/2960236/14252139/4acc09d6-fa86-11e5-9917-87978bde0b93.png)

**Comment by Hoffi1** [comment]
Yep, it's just an idea, got no better one yet.
For me as developer it's absolutely clear. :grinning: 
(complete it could be "3 / 3 + 2 - 1, 1 ?" with two on waiting list)

btw: On the My Attending symbols are tooltips showing the meaning. A third (red circle with white dot) is for "on waitonglist", and a forth (grey circle with white dot) for "unknown" - just for theoretical case of a wrong/unknown status.
Some strings maybe new and must be translated. :wink:

**Comment by jojo12** [comment]
[loud thinking] 
?invitation will only be possible from backend attendees? There should be a possibility to select and invite (and invite more users with one click).

**Comment by jojo12** [comment]
I have manually tested the comments too. Works fine in jem_myattendings.

**Comment by jojo12** [comment]
did you made more steps here?

**Comment by jojo12** [comment]
I don't know where you are with this sorry. If it's too complicated, then perhaps there could be a switch for each event, if clicking the button is "registering" or non-attending. The comment can be used anyway.
