### ISSUE TITLE
ACL view

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1042]
Perhaps I don't understand enough: Each event has a "Access=Zugriffsebene". Does this work with new ACL groups? And how? I tried and didn't succeed.
EDIT:
I am not sure but this time I succeeded :-(

**Comment by Hoffi1** [comment]
Hm...maybe this answer helps.
I tried to "merge" both Joomla ACL system and JEM settings. Because at the moment only J! ACLs on component level are supported JemUser::can() first checks Joomla permissions given on site or for JEM, e.g. if this user is member of J! group "Publisher". If user is permitted function returns with true.
If not JEM groups are checked, or the JEM settings.
So there are multiple ways to give users "do" permissions making it impossible to give a short but complete description on how it works.
