### ISSUE TITLE
problem mit thumbnail in JEM and Joomla 3.5.(1) 

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1043]
Hi, I encounter a problem with the thumbnail:
when I upload an event image, In frontend eventlist I only get a link to the normal image and no image!
Can this be a change in Joomla 3.5?
when I look in joomla/media I don't see the image only the name!
![imageprob](https://cloud.githubusercontent.com/assets/2960236/14425469/caa2ccba-ffe7-11e5-8091-4ea7d80eeee9.png)

**Comment by Hoffi1** [comment]
Hi Jojo,

I played around on J! 3.4.8, 3.5.0, and 3.5.1 but can't see any problem.
Uploaded (large) images on backend and frontend but see them all inside JEM views but also in Media view on backend.

But because Joomla's Media manager is independent from JEM and should simply show a preview of image files in given folder could it be that there is a problem with the image itself? Or with file permissions? (I played on Windows)

**Comment by jojo12** [comment]
Sorry, perhaps I wasn't clear: the big images work well, the small inside the small folders give pr

**Comment by Hoffi1** [comment]
The small images will be created if requested on frontend (by showing the event in list or details view).
If the resulting small images are wrong maybe you've a problem with GD2 lib on your server?
Or have you running an updated Zebra Image class? Currently I had only patched our old one.
Have you checked the files directly? Are they valid images and the filename extions (.jpg) matches the content (it's really a jpeg)? Or have you disabled Thumbnail support on JEM Settings and this gives this effect (I never tried it so far)?

Because you have a problem I would like to find the reason. So let me reopen it for tracking.

info: In Media Manager I saw all except one images in small version too. The exception was because I not refreshed the list on frontend so it was not created so far. But the created images looked correct.

**Comment by jojo12** [comment]
I tested now on a clean JEM2.1.5 install on Joomla 3.5.1. And I had not this problem. So it seems to be my problem! Don't waste time for that! You've better things to do.
Will test more and write here the results.

**Comment by Hoffi1** [comment]
Accepted. :smile:

**Comment by jojo12** [comment]
I looked more:
the normal image (not in /small) is ok. The thumbnail  ist there but the rights attrib are not normal (than earlier) All earlier thumbnails are 644. The new one has xx. When I change this attrib, then the image is ok.
So my question is: where comes this from (I am using J!3.5.1, php7 and JEM 2.1.5 +
![imgattrib](https://cloud.githubusercontent.com/assets/2960236/14581482/cd608978-03ee-11e6-8a88-7db7ec83eb0d.png)

**Comment by jojo12** [comment]
Finally I've updated to JEM 2.1.6 dev5. The problem is solved.
I don't know which mistake I made, but it's seems really to be only on my personal version. sorry.
I will close this.

**Comment by jojo12** [comment]
I reopen this because I tested with different browsers:
I tested after all with backend
The above mentioned problem was with firefox.
I tested then with internet explorer edge: no problems!
I tested then with chrome: here there is a very special comportment:
first in backend the preview image is there, but immediately after this, this image goes away.
And it will not be there in frontend. But the image is in mediacenter /small.
