### ISSUE TITLE
translation problem: mailer plugin

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1054]
what's the difference between:
originator and creator ?

in german it is both translated with Ersteller

But there must be a difference?

**Comment by Hoffi1** [comment]
Hm...there is a little difference. Originator is more an editor, a person which actually modified an item but may or may not the creator/owner of that item. If you look e.g. on leo.org you'll also find translations like "Absender" or "Bearbeiter".

Take the crazy use-case user A created an event which user B modified. Now the mailer sould send emails to the person which changed the event (user B) and the creator/owner of the event (user A). If both options are shown as "Ersteller" the admin will be confused.
In that case PLG_JEM_USER_CREATOR_LABEL="Originator" is the person which actually triggers the mailer e.g. by modifying an event (shown in sections "Email on update event/venue").
In sections Email on new event/venue PLG_JEM_USER_CREATOR_LABEL="Originator" is used where the user is both, the editor but because it's new stuff also the creator/owner.

btw: Please be warned, related to advanced registration some component and mailer texts will be changed soon. On mailer the content texts are involved / new one added to at least add the new comment. I hope I can commit tonight...

**Comment by jojo12** [comment]
Thanks
