### ISSUE TITLE
Add date and time to Attending-Manager for print/export

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1083]
Hi, it would be very helpful to add the actual date/time when printing/axporting the list of atttending/non-attending users.
So an event creator gets a list (and prove) when printing at the end of a registration limit date.

In german can this be e.g. in the title "Angemeldete Teilnehmer (Stand vom 31.8.2016, 15.15 Uhr)

**Comment by Hoffi1** [comment]
When I print a web page I've configured date as part of page footer so I never missed this info. :smile: 
But it should be no problem to add it on info block above the list (I also thought about whings like max. places, waiting list on/off or so).

But for csv export it's more difficult because that's only a table. So one can (mis)use the header line or add one or more "wrong" lines not containing a user but other information user must interprete different - not really a way I like...
Maybe we can add the date into file name?

**Comment by jojo12** [comment]
> Maybe we can add the date into file name?
yes

**Comment by jojo12** [comment]
for my own purposes the dev 3 is enough. Even when it's not yet finished, I will use it. 
We start with a new year in one week. And I will describe the users, how to use attending/non-attending.

**Comment by Hoffi1** [comment]
I hope I can fix some bugs you reported here until end of your year. :smile:

**Comment by Hoffi1** [comment]
...dachte ich mir schon. :smile:
