### ISSUE TITLE
dev4: question: what happens with attendees, when you change system

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1087]
My question, I don't try it:
when I have some registered attendees and then I change the system e.g. to no eventregistration,
what happens?
Are all the just registered persons deleted, or they are back, when you change back the system or?

**Comment by jojo12** [comment]
I tried a bit; general disabling of register, hides before registered users, they are back, when register is enabled.

**Comment by Hoffi1** [comment]
That's a bit of sort "undefined behavior". I mean, what should JEM do?
Because removing records from DB is a hard thing and it's not clear that the Admin expects exact this JEM will not delete any record from registers table. Instead registration feature will be switched off / not shown.
On frontend this should be consequent without exceptions. On backend it could be useful to allow Attendees view for Super Users (best with info text) - not sure what's implemented yet...

**Comment by jojo12** [comment]
For me: it's good that JEM doesn't delete the the registered users in DB. It's good that they are back, when reenabled registering. Perhaps the infotext in backend is a good idea.

(But It's really good this dev4-JEM 2.2. When does ist goes public?

**Comment by Hoffi1** [comment]
Thanks :bouquet: I would like to check compatibility to J! 3.6 before. (Kunena 5 makes me a bit nervous, but this version switch maybe accident)
Also someone whished an additional "registration cancellation until" option... :wink:
