### ISSUE TITLE
FR or help: How to order simplelist DESC as default?

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1088]
There are some people, they don't archive and have not so much events. They like to have the latest events on first place.

I tried in models/eventslist.php to change ASC to DESC, but nothing happened.

**Comment by Hoffi1** [comment]
For Simple list (eventslist) you have to change lines models/eventslist.php(111) and views/eventslist/view.html.php(61) from 
```if ($task == 'archive' && $filter_order == 'a.dates') {``` 
to 
```if ($filter_order == 'a.dates') {```
The model influences the ordering itself whereas the view shows the matching icon in Date column header.

Because it is the default (fallback) it only works as long as the user has not clicked anywhere. Maybe you need to logout/login to get a "fresh" user session.
