### ISSUE TITLE
FR: limitation of eventregistering

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1094]
There's a post in forum asking for that

**Comment by ernst67** [comment]
I created a suggestion in the tasklist, 2 weeks ago, just before my holiday:
http://www.joomlaeventmanager.net/project/tasklist-jem-2

**Comment by Hoffi1** [comment]
It seems you talk about two different things. "limitation of eventregistering" doesn't match "configurable Edit views" in my eyes.

Please give concrete description instead of vague links or references.

**Comment by jojo12** [comment]
ok, I found it:
Hi developers.
For a future version of JEM, it would be nice to get a limit to how late users can register for an event.
For instance: Users have to register for an event at least 24 hours before the start of that event.

This could be made with a default value per category, affecting all events in that category, unless one or more of those events gets a manual value change. For instance 24 hours could be the default value per category, and any event in that category can have the value changed from 24 hours to 48 hours.

I hope you appreciate suggestions B)

**Comment by Hoffi1** [comment]
Thanks @jojo12, I share your comment.

The first part, I think, is really missing and should be added. As we have an option "until [hours] before event starts" for registration cancelation we should also provide such an option for registration istself.

The category thing is a nice (and legitime) dream - but very difficult to develop. Not only because an event can have multiple categories - which one wins? And what if a categfory value will be changed later? I would suggest to keep it simple and understandable and only add such an option to editevent.

**Comment by ernst67** [comment]
@Hoffi,
Sorry, I misunderstood Jojo's initial post. Thought this was about something else..
