### ISSUE TITLE
2.1.7 dev 6: problem when adding an author to a sample event

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1096]
Hi, I just mentioned that an issue before:
when adding a user as author to a sample event, I get the notification:
Warnung
JUser: :_load: Fehler beim Laden des Benutzers mit der ID: -- (cleaned: because it's the ID of the admin)

But adding this user as author is possible.

**Comment by Hoffi1** [comment]
What do you mean with "adding a user as author"? Where are you? Backend - Edit event - set admin as event creator? Please give me where-to.click instructions for re-play...

btw: Is the ID the correct one?

**Comment by jojo12** [comment]
After a clean JEM install, then with the loadsample, no author (proprietar) of the event is defined. 
So I had to go to the BACKEND and assign an event to a user (me).
If not I have no own event in myevents view. (And can't test your new possibilities.)
Then the notification appears.

**Comment by jojo12** [comment]
I looked a bit more, and yes in this site there is no user with that ID, but it says:
JUser: :_load: Fehler beim Laden des Benutzers mit der ID: 62
This seems not to concern the new added possibilities. It has more to do (I think) with loadsample...

**Comment by Hoffi1** [comment]
Hm... normally sample events should get super user's id on import.
Maybe when importing own exports data isn't touched but on sample data it should because each site may have different ids.

**Comment by Hoffi1** [comment]
Ok, I think it's because your "Super User" has married and taken the name of his wife. :grinning: 
The model tried to replace 62 from sql file to the id of site's Super User - by searching for exact this name.

I think the person able to install sampledata should be an admin so I use current user's id as fallback if this user is allowed to manage JEM.

So if you import sampledata with this fix it will set you as creator of events and venues. The message you refer to above comes from Joomla and will be shown on all "old" entries as long as unknown ids are stored.
