### ISSUE TITLE
bug?: meta-tags for categories/subcategories does this work

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1106]
There is a post in the forum, who says, this doesn't work. At least in russian language.
I've not much experience with meta tags. Normally I let it like it is.

If someone is experienced with that: can you test, if this works as it should, please!

**Comment by diesl** [comment]
> There is a post in the forum, who says, this doesn't work.

Can you please add a link to the post and the detailed error description?

**Comment by jojo12** [comment]
look for a post of "brandonlang" september 21.
http://www.joomlaeventmanager.net/forum/jem-2-2-x-on-joomla-3/9906-meta-tags-in-a-component-don-t-work#22619

**Comment by Hoffi1** [comment]
I played around a bit and generally it works if meta fields of **category** are used.

If one uses the meta fields of **menu item** there could be problems because they are not (in all views) integrated.

Fixing this is a bit tricky because the active menu item could exactly match the category id or not (in case of a sub category without own menu item). There must be a clever but logical strategy when which meta data should be shown.
(I would suggest: show meta data of (1) exactly matching menu item else (2) category else (3) menu item else (4) global.)
