### ISSUE TITLE
Use of substr() for utf-8 encoded strings

### ISSUE THREAD

**Issue by diesl** [jemproject/JEM-Project#1113]
We use `substr()` function for utf-8 encoded strings in several places. This function is not designed for multibyte strings like for example, utf-8.

We have to use php's `mb_substr()` function or Joomla's `JString::substr()` function which is also suited for utf-8 strings.

**Comment by jojo12** [comment]
I tried with mb_substr() and it shows now uft-8. Thanks.

**Comment by Hoffi1** [comment]
Yes, you're right. I already tested with umlauts but not on border so I hadn't seen the substr() problem.

Now I prepended JString or removed the truncation (e.g. on csv export it was not required because db already limit the strings). Other files I've not touched because there will be no conflict.

One thing I'm not sure is site/views/event/view.html.php(278ff). Theoretically code for closing bracket could be part of a multi-byte character but I don't know if ```explode()``` is safe or how to replace it if not.

**Comment by Hoffi1** [comment]
**Attention!**
JString::substr(str offset, length) works different than PHP's substr(str, offset, length) !
If length is FALSE (e.g. as result of a (JString::)strpos() call where needle wasn't found) substr() returns an empty string, but JString::substr() returns the substring from offset to end of string as if length wasn't given.
