### ISSUE TITLE
 PHP 7.1: Warning: A non-numeric value encountered in...helper

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1120]
Hi, using php 7.1 during changing to a new page, I get this warning. After refreshing it's away.
I found something which says this is coming form php7.1.
Warning: A non-numeric value encountered in mysite.ch/httpdocs/components/com_jem/helpers/helper.php on line 147

**Comment by Hoffi1** [comment]
Hi Jojo,
I've not seen such problem on any PHP version incl. 7.1. Line 147 is within the cleanup function. If you set JEM - Settings - Global Parameters - Write Logfile to Debug or All you should see an entry within the JEM log file (folder logs or log on your site, as configured ion Joomla). Important would be "last update." and "tz-offset:", which must be numbers too. Maybe you must wait until tomorrow because it's only printed once per day.
The second one is got from idate() which always returns an integer, as the php manual says.
The first one comes from db table *_jem_config which theoretically could be anything. (adding ```WHERE keyname = 'lastupdate'``` maybe helpful 😄 ) - but I would expect that it "heals" themself after successful cleanup.
------------------ some seconds later -------------
I think I got it.
The sql file used for fresh installation sets lastiupdate to an empty string which is not really a numeric value. As result the cleaup is made which finally sets the actual timestamp as lastupdate so this message is shown only once per fresh installation.
To reduce it to zero I would adapt the sql file and/or explicitely cast the value to ```int``` to tolerate admins playing around within the db tables. 😉 

Thanks for finding it @jojo12 👍
