### ISSUE TITLE
FE: event creator can't change invited user to attending/non-attending user

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1129]
to change an invited user to a attending or non-attendinge user, there is no other possibility than to delete the invited user and add the same user as attending or non-attending.
This could be enhanced?

**Comment by Hoffi1** [comment]
You're right. This doesn't make sense because generally you can register a user with any state by removing current registration first.

Because one can change from invited to attending or not attending it won't be possible to make invited icon clickable (as registered vs. waitinglist icons). Instead I'll make it possible to use Add icon / popup to change registrations.

**Comment by jojo12** [comment]
Hi, this works fine (first I needed to read your explanation)
