### ISSUE TITLE
dev8: it's a pity, that models/event.php isn't adapted for attending/non-attending view 

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1132]
Hi, I installed dev 8,
thanks for the models adaptions to use overrides: 
but it's a pity, that changes to make visible non-attending, invited status can like that non be shown.

**Comment by Hoffi1** [comment]
You're right, this was never part of official JEM.

I enhanced model and view yet to allow template overrides to list registered users with other states too.
Instead of ```$this->registeres``` one can use ```$this->regs['XXX']``` where 'XXX' can be 'all' for all together ot 'invited', 'not_attending', 'attending', 'waiting' for users with such state.

**Comment by jojo12** [comment]
Help!
I used the models/event.php and the views/event/view.html.php. Then I adapted my template override
inside the foreach with:
if ($this->regs['attending']) ...
if ($this->regs['non_attending']) ....
if ($this->regs['invited'])  ...

but now I get three times the same logged in user (superuser) with three different statuses!
What does I make wrong!

**Comment by Hoffi1** [comment]
@jojo12 , I don't know exact your override but related to the original default_attendees.php you can

(a) to show all within one single foreach but with additional text, icon or whatever
replace ```foreach ($this->registers as $register)``` with ```foreach ($this->regs['all'] as $register)```
and within the loop have something like ```if ($register->status == 1) { echo 'attending'; } elseif ($register->status == -1) { echo "not attending"; }``` and so on (0 = invited, 2 = waiting)
(instead of the ```if```'s you can use ```switch ($register->status) { case -1: echo 'not attending'; break; case 0: ...``` of course)

(b) to have a dedicated area for each status use multiple foreach blocks like
```foreach ($this->regs['attending'] as $register)``` ...and within ```echo 'attending';``` (or for test ```echo $register->status;```) and so on.

```$this->regs['all']``` contains all users and you have to check the status.
```$this->regs['waiting']``` for example contains only users on waitiing list (status 2) so there you don't need to check status.

**Comment by jojo12** [comment]
Thanks, it works, I am trying around: waitinglist I didn't success until now. Rereading your post!
