### ISSUE TITLE
licence raw

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1160]
Accidentally I've seen, that our licence raw:
 * @license http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL
leads to an error 404

when I look into the actual joomla files I see no link
 * @license     GNU General Public License version 2 or later; see LICENSE.txt

My question: Do we have to update that?

**Comment by Hoffi1** [comment]
The problem is that the protocol has changed from ```http``` to ```https```. If someone types in ```www.gnu.org/licenses/gpl-2.0.html``` it would also work.
Changing all these lines to those as you find on Joomla files is not really a better solution, I would say. Because the text says "version 2 or later" but LICENSE.txt is exact version 2, June 1991 and does not provide any link, only a postal address.
Each xml contains a valid email address and url to our site so everybody can contact us and ask for the license.

I think it would be enough to correct ```http``` to ```https``` on at least all xml files.
