### ISSUE TITLE
de-DE_JEM 2.2.X non-attending mail has no text (only when no comment) (with JOOMLA! 3.7+)

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1164]
URGENT
in JEM 2.2.1 and JEM 2.2.2 when a user is saying, he is not attending and he don't add a comment, in the email is no text

**Comment by Hoffi1** [comment]
This problem is within the german translation. Because of the "description" part there is one "%s" too much.

But there is another problem within mailer code itself:
In case of user (un)registration with comment parameters in admin (non-attendee) mails are mispositioned. Instead of url wrongly the description is shown so that url is below "Thank you".

**Comment by Hoffi1** [comment]
That means: PLG_JEM_MAILER_ADMIN_REG_NOT_ATTEND_BODY_9 must be fixed too in german translation file (by removing "\n\nBeschreibung:\n%s").

**Comment by jojo12** [comment]
> Instead of url wrongly the description is shown so that url is below "Thank you"
Yes. but not only this. In more than one case, the url is after the "Danke"

I absolutely don't understand the system with the %s. Where can I get some hints for that?

**Comment by Hoffi1** [comment]
That's simple. 😉 Each %s will be replaced by a string. If you look into mailer.php, e.g. around line 175 you'll see some lines with ```JText::sprintf($text_body, ...)```. $text_body refers to a string from translation file, e.g. PLG_JEM_MAILER_USER_REG_NOT_ATTEND_BODY_A which contains 10 %s (A == 10). The corresponding sprintf has 10 parameters behind $text_body which replace each %s in the same order. In this example we have user/attendee, comment, event title, date, time, venue, city, description, link, and site name.
Other users will get the PLG_JEM_MAILER_ADMIN_REG_NOT_ATTEND_BODY_9 text with 9 %s because no description is sent.

The bug in mailer.php was to have some sprintf with $text_description paramter but _ADMIN_ text without a %s for that. sprintf tolerates too many parameters but returns an empty string if not enough parameters are given. So you have no text or chaotic text if these two counts doesn't exactly match.
