### ISSUE TITLE
JEM 2.2.2 jemlistevents enhancing for enddates

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1169]
hekla proposed in the forum:
to get the enddate too, when this is another day, replace line 331 and 332 with:

`$html_list .= JemOutput::formatdate($event->dates, $parameters['date_format']);
if ($event->dates != $event->enddates) {
   $html_list .= " - ".JemOutput::formatdate($event->enddates, $parameters['date_format']);
}
$html_list .= (($parameters['show_date'] === 'link') ? '</a>' : '');`

**Comment by Hoffi1** [comment]
The problem is we have dedicated columns for date and time which could cause confusion.
In that case it would be better to show a single date/time column as in component's list views.
This could mean:
- additional parameter [enddatetime=on|off] as well as "Show end date/time Yes | No" setting
- if this is on end date and/or end time will be shown depending on date and time parameters
- param "date=link" will become a bit difficult but it's possible too () link to start day or end day, not to range, of course. (oh I see the feature requests coming in...)

**Comment by jojo12** [comment]
works fine!
