### ISSUE TITLE
adding jpeg as allowed image file

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1173]
from a post in the forum:

Could you add the jpeg extension as an allowed file format. Now only png, gif and jpg are only excepted.
This could be easily achieved by adding "jpeg" to the image.class.php file, line 237:

change:
`$allowable = array ('gif', 'jpg', 'png');`

to:
`$allowable = array ('gif', 'jpg', 'jpeg', 'png');`

**Comment by Hoffi1** [comment]
That's not so easy. Additionally two table classes and three modules must be adapted.
BUT if you also want to use "modal window" e.g. on modules you must also patch modal.js provided by Joomla! Otherwise you see the jpeg file as "textual description".

I add an option on JEM Settings - Basic Settings - Image Handling where user can list all extensions allowed. The user changes this on own risk! We can't give any guarantee for extensions other than jpg, gif, png.

will become available with v2.2.3-dev3

**Comment by stimpsonjcat** [comment]
Maybe I don't understanding you correctly, but aren't you making things more difficult than needed? It's not about allowing _any_ filetype to be the image associated with the event, it's just allowing gif, jpg and png. But jpg files can have two types of extensions in the file name: .jpg or .jpeg. The image.class.php file has a function to check the filetype, but seems to do this based on file extension. Since jpeg is not allowed, als noted above, it will reject perfectly good jpg files, which have a .jpeg extension. I did alter line 237 as stated above, and now jpeg is accepted.  
Or am I missing something here?
