### ISSUE TITLE
adding "Save as a copy" in frontend eventedit

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1175]
Hi, on one of my sites I had to insert in frontend a lot of same events on different dates but not in a rule.
It would be very helpful to add such button. So you can open an existing event give a new date and save it.
This would save a lot of time!
Is this too much work or is this possible?
I think editvenue doesn't need this.

**Comment by Hoffi1** [comment]
At first: Happy X-mas. 🎅 🎄 

Generally Joomla's philosophy for such tasks is to use the backend. As far as I can see there is no way to e.g. copy an article on frontend.
But personally I would reluctantly give non-admins access to backend so yes, such an option on frontend would be useful.
The most difficult part is the access rights management because e.g. "Edit own event" and "Create new event" can have different permissions. Also I'm not sure, if I prefer "Save as Copy" button to click after modifications or better "Create a Copy" button to open Edit view (background: sometimes I "destroyed" events by clicking "Save" instead of "Save as Copy", so an early and single decision could help to prevent such mistakes). I have to take a look and think more about this...

**Comment by ernst67** [comment]
I like the idea.. but I'm a little afraid such a function would lead to a lot of "Copy of ...." events. 
Hoffi's suggestion might be a good one to reduce that risk.
User that still make a mistake would have to be allowed to delete their own event as well I guess.... 

Did I yet say Merry Christmas? :-D

**Comment by jojo12** [comment]
sorry, I am late merry christmas and thank you very much for all you did for JEM. I know you give always your best for the users of JEM.

**Comment by jojo12** [comment]
Hi, I made a 2.2.3-rc1 package (I could not wait) and tried. All install ok. Coming from eventslist, the copy event seems ok.
My question: coming from calendar should have this possibility too, is this possible?
(I am not technician: I first thought, "save as a copy" should be inside of eventedit), but it's ok like that.

My other thought: In my eyes "save as a copy" is not needed for the venue, but perhaps I am wrong. I can't see the circumstances you need that!

**Comment by Hoffi1** [comment]
Not sure if I understand your question. The Copy icon is only shown on Details view, regardless if you enteres this view from a list, calendar, module or whatever. But maybe you meant the optional Add and Edit icons directly within calendar views? There the Copy icon is not showable yet because I found it too much for these little areas. But if I think more about this and the use-case I had in my minds (using calendar view to plan next events) it could be useful and consequent to add an option to show this Icon too. I think I'll think a bit more about this...

Regarding "Save as copy": I temporarly tried to implement this Joomla-default way. But especially on such complicated things like JEM events with recurrence, registrations etc. it's horrible. Example: You've an event with e.g. 3 attendies, 2 invited, and maybe some more, enter Edit view, change the date and press "Save as copy". How should JEM react? Take you as the master and send emails to the 5 registered persons to inform about their invitation/attendance? Or should it think "users are stupid" and silently removes all registrations? I found no solution so I decided to let JEM prepare a copy of the event which then the user can accept and modify so it's clarified what's finally saved (incl. notification emails).

Regarding "Copy venue": I agree, in 99.99% nobody needs this function. But it was easy to implement (nearly identical to event stuff, just more simple). And with one million installations we would make around 100 people happy with this function. 😉

**Comment by jojo12** [comment]
You're right with the detail view. My mistake: I choosed in the calendar the add event image. But opening the detail view of an event, all is there and I can copy the event. Super! Thanks a lot! Very good. Excellent!
I can now propose the venue calendar as "Raumbelegungsplan". And the responsible persons don't need to enter into the backend.
