### ISSUE TITLE
discussion: view attendees comment for all in FE

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1193]
@kralyk wrote:
Hello,
I have a suggestion for one improvement:

Displaying user comments in view event (which users write during registration) in a listing of all attended and unattended people?

Would it be set up within these adjustments?

Optionally even with the ability to enable or disable this view (eg only for guest, registered, etc.) in the JEM administration.

I think it would be a great improvement.

Thank you and kind regards.

**Comment by jojo12** [comment]
@kralyk wrote:
I'm sorry, I've seen here that settings for attended and unattended viewing will be. So please put it in the right place, I do not know much about github.

My opinion: In my case, these comments are information for other users as well, for example

    that someone will come to the event later
    He takes another person
    why not come, etc.

Personally, with JEM, I organize a meeting of our sports section in the gym, weekend trips, etc. - so I consider this information important also for other JEM users.

So, in my case, it's not private information, so I need this information to display in the frontend best right in view event.

And if someone considers it private information then it would be possible to view only for registered, admin or guest, etc.

**Comment by jojo12** [comment]
I experienced abuse even with JEM comments plugin. I had ads and bad texts which were seen publicly.
I think the majority of our users don't want this free possibility to post.
The author of the event (and the site administrator) have to know the comments. And they can see it in the FE. That's enough!

**Comment by Egnarts94** [comment]
I think this Topic touches a very big field. The field of registration for an event. There is a big ToDo for JEM.
Actually it's just rudimental and could be much more complex with much more options.
In my opinion we should let it be as it is and search for a possibility to integrate breeezing forms (like you did jojo) or visforms via a plugin like other 3rd party plugins.

**Comment by Kralyk** [comment]
JOJO12 , I do not know if we do well.
In our group what JEM uses, everyone wants their comments (which they write when registering for the event) are best visible to everyone directly in event views. Because it is in our case information that is not private but necessary for other attendees. 
I would only need to see comments in the names of attendees, etc., if possible in the event views (in FE), or if you want to set in BE if these comments are to be visible to anyone or just to someone (registered, admin, etc.)

We also use the JEM plugin plugin (with jcomments), but I have a couple of comments to it:

- but I still have to have Kunena forum (with kunena discuss), so I have to "uselessly" use the latest posts from two different forums because the JEM comments plugin does not support Kunena.
- I do not have a spam problem because only registered users can contribute.

It is only a theme for further development of JEM.
I hope I explained this more clearly, my English is not very good.

**Comment by Kralyk** [comment]
Egnarts94 
I thought it this way:

In BE, the admin sees a list of attendees with their comments - it works.
And I would like to see the same list in event view in FE visible to all users (registered or guest) - I do not think there is a need for any third-party forms. Now only the attendees names are shown in the event view, so it would be enough to add comments.
But I am not a programmer, so I can not program it .... :-(

**Comment by jojo12** [comment]
I think, this should be a possibility for an template override, because it is a very special case (with the risk of the owner of this site). So we could help how he can do it. But newer as an official JEM.

**Comment by Kralyk** [comment]
jojo12,
I still do not understand what I risk by having listed attendees comments in event view?
Can you explain this to me?

**Comment by Egnarts94** [comment]
What do you think about a compromise?
I will extend the model to also get the comment from the database. So it is easy available for a template override. You need just add "$register->comment" to the override and the comments will be shown in the event.

**Comment by jojo12** [comment]
I can accept this. If someone wants that, he can make an override. And because the model is prepared for that, there's no problem with updates.

**Comment by Kralyk** [comment]
Egnarts94: 
Thank you for your work. I do not know exactly how to set override now, but I'll figure it out when this version is finished.
