### ISSUE TITLE
Cancel button inactive @ mail to a friend

### ISSUE THREAD

**Issue by jobrusche** [jemproject/JEM-Project#1562]
JEM 2.3.17 
Cancel button in "Mail to a friend"-popup window is inactive.
There is now a "Close" button (not present in 2.3.6)

**Comment by Heklaterriol** [comment]
Just checked: Already in JEM 2.3.5 / J3 it was not working.
The problem is, that it is a modal window with an iframe inside it. The close button for the modal window is located within the content of the iframe. This is a bit complicated.

Sugestion:
We remove the "Cancel" button.
Reason: We already have a "X" top right and a "close" button in bottom right.

What do you think?

**Comment by jojo12** [comment]
I can live with your proposal

**Comment by mckillo** [comment]
I agree too. See commit above

![JEM4-close_for_email_popup](https://github.com/jemproject/JEM-Project/assets/2765316/5caf655d-1729-411c-b13c-4fd6f8bacef7)
