### ISSUE TITLE
is the zip file inside the code so that it can be used as package?

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1596]
I ask because there was some time ago, that I took this and then it did not install the plugìnd and modules.

**Comment by Heklaterriol** [comment]
I do not understand the question "is the zip file inside the code so that it can be used as package?"

The zip file [pkg_jem_v4.0rc1.zip](https://github.com/jemproject/JEM-Project/blob/JEM-for-Joomla-4/pkg_jem_v4.0rc1.zip) is the _JEM 4.0 Release Candidate 1_ released 2023-06-04, if this is the question.

**Comment by jojo12** [comment]
Sorry, I ask because there were problems when I took 2.3.6 to joomlaeventmanager.net. And I don't want to repeat that. E.g.inside of git on the right side in master there is only 2.3.5. I don?t know why.
