### ISSUE TITLE
booking a whole serie of events (course) is not possible

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1613]
See post #30568 in joomlaeventmanager.net

**Comment by mckillo** [comment]
What link? we don't have this number in issues.

**Comment by jojo12** [comment]
in joomlaeventmanager.net

**Comment by mckillo** [comment]
I find in the search of forum, I don't find anything about 30568
I search by keyword, https://www.joomlaeventmanager.net/forum/bugs/30568, 
How to serach a post in kukena? in there isn't option in the search tab by number post.
Send me the link.

**Comment by mckillo** [comment]
I find it
https://www.joomlaeventmanager.net/forum/jem-4-x-for-joomla-4-community-support/12383-booking-all-events-in-a-serie#30568

**Comment by mckillo** [comment]
It could be because JEM knows if the event is recurrent or not, if this event is the first recurrence or not. 
We could be for this type of recurrent event by asking the user in the registration form:
Do you want to register for this  event or in all series event (course)?
In this case, the management error is complex, because it will pendent of free places for each event, and we must shown the disponibility table for recurence events list.
I think that it could be a proposal new feature to discuss in dev for JEM v.4.1.0

**Comment by jojo12** [comment]
I fear, then we have to change too much! After making a recurrence, the events are separated, e.g. I never can add something for all events in the whole serie.

**Comment by mckillo** [comment]
I know, but it's possible, for registratation of event incomming and to change something for all events. 
For that, it's a proposal with complex level and need time to dev if it's aprovated. I think that before there are others priorities.

**Comment by mckillo** [comment]
Open bugs (patch about datetime for JEM v.3.x as pctech), microdata, add event image popup, add image select of server (frontend),  review javascript code, redesign views (attach files), improve event types and others features in branchs opened.
There are a lot of tasks to do ;-)

**Comment by jojo12** [comment]
Please don't forget your real life!

**Comment by mckillo** [comment]
This is solved wirh #1764
It can be clases.
