### ISSUE TITLE
JEM 4.0.0+: no possibility, to directly say NO, I don't participate

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1626]
when a user decides to give feedback to participate to an event, there is not yet an entry in xxx_jem_register.
When he is invited, there is an entry with status=0 (and waiting=0)
When he says, he will participate, then there is an entry with status=1 (and waiting=0)
When he says, he will participate, but he is on the waitinglist, there is an entry with status=1 and waiting=1
When he stores his attending, then the entry is changed to status=-1 (and waiting=0)

**The problem is: when he directly says, he will not participate, there is not yet an entry which can be changed. The program should write a new entry with status=-1 (and waiting=0)**

It should be possible, that users can say, they will be absent! For example in a class: normally all are attended, only those who are not able to attend, should answer

**Comment by mckillo** [comment]
I think that this a design error, before "request-answer feauture" (branch doesn't merge), the user options in the registration event were "YES|NO", if one user (not registered), select NO, it's a error because the user wasn't any registration.

Fix the design error, now, the negative of user is saved in register table. 

I think that the complementary solution is merge the "request-apply" branch, because if we apply, the admin can setting it is necesary to know if the user doesn't go to the event.  

Tell me, if it's is good the commit (see above).

**Comment by jojo12** [comment]
I tested in 4.0.1-dev1 and this is works fine now, lot of thanks.
