### ISSUE TITLE
Field and Number Logic in Registration

### ISSUE THREAD

**Issue by Heklaterriol** [jemproject/JEM-Project#1628]
I added a javascript snipptet to the backend registration with the following functionalites:

- If "Registration" is "No" then do not display the rest of the registration fields.
- the number in the input field "Minimum booked per user" cannot be greater than the one in "Max Places"
- the number in the input field "Maxium booked per user" cannot be greater than the one in "Max Places"
- the number in the input field "Minimum booked per user" cannot be greater than the one in "Maxium booked per user"
- the number in the input field "Maxium booked per user" cannot be lower than the one in "Minimum booked per user"
- the number in the input field "Reserved Places" cannot be greater than the one in "Max Places"

Frontend will follow.

**Comment by jojo12** [comment]
Well done! 😉

**Comment by mckillo** [comment]
Sorry, but I suposse that I don't have all info about this issue. I don't know what is the necessity in backend to run javascript in this view and why I need that the admin navigator runs this script into edit event view (backend), because the backend does those calculations, checks and limitations of min&max of the fields during the view display and save process.
Be careful with the some string are used in the view as title field. I think taht it's better to do code of view by php.

**Comment by Heklaterriol** [comment]
@mckillo 
It was possible to enter and save contradicting and useless numbers in the registration settings, like:

![Ohne Titel](https://github.com/jemproject/JEM-Project/assets/28540581/939d38c3-7dc7-435c-86fb-a37a8a3aace7)

The script just checks the entries acccording to the criteria in the first post.

**Comment by mckillo** [comment]
Yes, it can save this setting from the frontend and backend, because these values of form attributes are saved by Joomla Core, 
In the beginning, when I read the issues, I thought there was an error in the booking places feature.

All fields of the model-form are saved on the same way in Joomla (core and extensions).
In general, the extensions do not check the values indicated by the administrator in the fields, nor the possible combinations. The fields are already defined and limited in the xml files. I don't know if it is possible to make min and max declarations with references to the value that has other fields, I think not (I would have to see the code in Joomla and as error control is low priority for admin setting).

Then, if we want to check that the admin writes in these fields, I agree with you, it is an improvement to avoid errors and at the end you have more control about the limitations of values. Good job.

**Comment by jojo12** [comment]
I am not a dev, so I am confident!
