### ISSUE TITLE
booking needs more testing

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1655]
It needs more testing

**Comment by jojo12** [comment]
I add a zipfile with changes of default_attendees.php and default_regform.php (legacy and responsive). Please test!
[event.zip](https://github.com/jemproject/JEM-Project/files/12609647/event.zip)

**Comment by jojo12** [comment]
There is an error:
When a user is "attending, but on waitinglist"
and he is booking more places, then he is on attendinglist included with his additional places.
(my setting was: waitinglist=yes, request answer=no max.places/user=3, max.places/event=0 (unlimited)
I add my test paper
[Tests regform in DE.pdf](https://github.com/jemproject/JEM-Project/files/12729613/Tests.regform.in.DE.pdf)

**Comment by mckillo** [comment]
I think that this issue is solved, is it right?

**Comment by mckillo** [comment]
@jojo12  I have added part of your change (zip files). Change your message button as warning message because
 this text isn't a button.
 
![20231029 JEM 411 - Message warning in answer of registration](https://github.com/jemproject/JEM-Project/assets/2765316/ad751bed-0581-49f6-83bd-660d0b3f770d)

This commit has:
- Review code and improve the booking system.
- Review and add string (your zip). 
- Now the waiting places counter is right.
- When there aren't more places to the user, show a warning message.
- When the answer is request to the user, show a warning message.

Apply changes to responsive and legacy styles.
If you have time, review and check.

**Comment by jojo12** [comment]
you're right it should be not a button (I made it just before in my).

But I would propose to add this colored warning, in the both default_regforms.php too!

**Comment by mckillo** [comment]
But the  <`span class="badge bg-warning text-dark" role="alert">` is applied in both files (responsive and legacy style).
