### ISSUE TITLE
new branch "JEM-for-J5"

### ISSUE THREAD

**Issue by Heklaterriol** [jemproject/JEM-Project#1675]
<s>Here it is: https://github.com/jemproject/JEM-Project/tree/JEM-for-J5</s>

Also discussed below: We have now a branch 4.2 which we make run on Joomla 5. See: 
https://github.com/jemproject/JEM-Project/tree/JEM-4.2-dev

**Comment by mckillo** [comment]
I don't know, if it's necessary, because the code don't change. J4 and J5 almost are the same, and one feature of J5 is that the extension fo J4 are supported in J5. If the JEM version doesn't change, I think, that we don't need to open other branch for J5. I prefer, close the 4.1.1 update version (including support J5 RC2) and open other branch for new JEM 4.1.2 with check support J5 as main feature.

**Comment by Heklaterriol** [comment]
Good point.
So we create JEM 4.1.2 and make it run on Joomla 5.

**Comment by Heklaterriol** [comment]
Update:
As J5 compatibility is more than fixes, the branch should be numbered with **4.2**

**Comment by Heklaterriol** [comment]
See: https://github.com/jemproject/JEM-Project/tree/JEM-4.2-dev
