### ISSUE TITLE
would be better: settings >event page> "display venue" show/hide instead of "display venue description" show/hide

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1683]
There are cases, you do not want venue details in event detail view, you have the venue in the event and you can link it to venue details.
so it needs a button to hide venue details in event view.
the button for venue description in global parameters>venues is ok.
if not it needs a new button

**Comment by mckillo** [comment]
You need for it a new button global parameters in **JEM->Setting->Event Page->Venues->Display Venue** because the Event Page->Venues->Display Venue Description has its function, and you want to hide all venue info in event view.

I think that this new option is global in the setting, but I think in the event setting. So, you can have a global setting as show and any event with venue info in hide or inverse.

**Comment by mckillo** [comment]
![20231028 JEM411 - New option to show-hide info of venues and registration in event view](https://github.com/jemproject/JEM-Project/assets/2765316/84e7658c-1ce4-4513-b89d-073339642907)

Here you are. I added the option for registration info. So, the config is more flexible.
Change was applied in responsive and legacy style.

**Comment by jojo12** [comment]
well done!!! thanks
