### ISSUE TITLE
 modules in responsive layout load both css files

### ISSUE THREAD

**Issue by Heklaterriol** [jemproject/JEM-Project#1691]
both the css file from the legacy layout and from the responsive layout.
That is not necessary – the responsive css file is sufficient.

**Comment by mckillo** [comment]
I want to assume that the idea of ​​the design was that they were independent, in case the module can be configured with one style or another, instead of globally. I don't know. 
If I compare the CSS of each module, there is everything, different combinations of content. There are even some that do not have responsive.
If you want to simplify, one CSS file will be enough in the root.
If you would like to have CSS for each style and other futures, then it's clearer to have each one in its CSS file.

**Comment by mckillo** [comment]
@Heklaterriol Test it when you can, tell me if it's right so.

Now, all JEM modules load only one CSS file for layout styling in the following order:
1. Template: /templates/cassiopeia/html/mod_jem/mod_jem.css
2. Media: /media/mod_jem/css/mod_jem.css
3. Module: /modules/mod_jem/tmpl/mod_jem_cal.css

'Cassiopeia' is the default template name, but it can be different.

If the layout style is responsive, the path changes to:
1. Template: /templates/cassiopeia/html/mod_jem/responsive/mod_jem.css
2. Media: /media/mod_jem/css/responsive/mod_jem.css
3. Module: /modules/mod_jem/tmpl/responsive/mod_jem_cal.css
