### ISSUE TITLE
Install JEM in Joom 5 without backward compatibility plugin: errors

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1703]
I installed a fresh Joomla 5.02 and deactivated the plugin Behaviour - Backward Compatibility. All works well.
Then I install the latest JEM package.

**Comment by mckillo** [comment]
Please, you don't deactivate the plugin Behaviour - Backward Compatibility because in this case, JEM doesn't support J5 API native.
The JEM code are supports J4 and J5, The JEM plugins code wasn't changed to J5API. 
How you can read in this Joomla article: https://manual.joomla.org/migrations/44-50/compat-plugin 
This plugin helps to support J4 plugin and JEM can be live in J4 & J5. "This gives extension developers or own developments additional 2 years time to update old code to the current standard."
In J6, the plugin of J4 doesn't support because in "J6 it's planned that deprecated code get removed finally".

_Workaround_:
If you want to solve part of the issue, edit \plugins\content\jem\jem.php
and add this line in the beginning:
`use Joomla\CMS\Plugin\CMSPlugin;`
and change the extends in the class to:
`class plgContentJem extends CMSPlugin`

With these lines, you don't have the issue in the plugin, but there are change other lines in the view and model, and plugin structure too. In the future, with the J6 beta (if not, JEM should have one version for J4 and other one for J5).

**Comment by mckillo** [comment]
@jojo12 I think that this issue can be closed.

**Comment by jojo12** [comment]
not fixed, I got:

Jclass not found

# | Function | Location
-- | -- | --
1 | () | JROOT/plugins/content/jem/jem.php:21
2 | require_once() | JROOT/libraries/src/Extension/ExtensionManagerTrait.php:217
3 | Joomla\CMS\Application\CMSApplication->loadPluginFromFilesystem() | JROOT/libraries/src/Extension/ExtensionManagerTrait.php:160
4 | Joomla\CMS\Application\CMSApplication->loadExtension() | JROOT/libraries/src/Extension/ExtensionManagerTrait.php:99
5 | Joomla\CMS\Application\CMSApplication->bootPlugin() | JROOT/libraries/src/Plugin/PluginHelper.php:232
6 | Joomla\CMS\Plugin\PluginHelper::import() | JROOT/libraries/src/Plugin/PluginHelper.php:192
7 | Joomla\CMS\Plugin\PluginHelper::importPlugin() | JROOT/libraries/src/MVC/Model/FormBehaviorTrait.php:193
8 | Joomla\CMS\MVC\Model\ListModel->preprocessForm() | JROOT/libraries/src/MVC/Model/FormBehaviorTrait.php:115
9 | Joomla\CMS\MVC\Model\ListModel->loadForm() | JROOT/libraries/src/MVC/Model/ListModel.php:431
10 | Joomla\CMS\MVC\Model\ListModel->getFilterForm() | JROOT/libraries/src/MVC/View/AbstractView.php:159
11 | Joomla\CMS\MVC\View\AbstractView->get() | JROOT/administrator/components/com_plugins/src/View/Plugins/HtmlView.php:80
12 | Joomla\Component\Plugins\Administrator\View\Plugins\HtmlView->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:697
13 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT/administrator/components/com_plugins/src/Controller/DisplayController.php:65
14 | Joomla\Component\Plugins\Administrator\Controller\DisplayController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:730
15 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:143
16 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
17 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:150
18 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:195
19 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:306
20 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:58
21 | require_once() | JROOT/administrator/index.php:32

**Comment by mckillo** [comment]
OK, check plugin files.... give a moment

**Comment by mckillo** [comment]
I have to upload a big commit with more update from J function to use...
I'll try to do it tomorrow, today I don't have time.

**Comment by jojo12** [comment]
in plugin jemlistevents.php line 16 there is a Class "JModelLegacy" not found

**Comment by jojo12** [comment]
[administrator/components/com_jem/views/help/tmpl/default.php ](file://///home/folktanz/public_html/administrator/components/com_jem/views/help/tmpl/default.php#L15)(line 15)
this is doubled-->gives an error!

**Comment by jojo12** [comment]
was an other (new) typo CMSMPlugin instead of CMSPlugin. I corrected
commit 2f8272e
