### ISSUE TITLE
4.2.2 Question

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1721]
I am trying to develop a JEM which doesn't need the backward plugin. 
Is this right?: 
when I get an error e.g. `"class JDate not found"` that I have to insert `"use Joomla\CMS\Date\Date;"` AND to exchange 'JDate' with 'Date'?
In the plugin behaviour/compat/src/classmap there is a classmap.php which shows all these classes we have to exchange until J!6
and so to procede with all such errors?

**Comment by mckillo** [comment]
If you need to change 'class J...' (J3/J4) to 'use ...' (J4/J5), you can use this reference link:
https://manual.joomla.org/migrations/44-50/compat-plugin/ 

When J6 goes out and J4 end of life, this backward plugin should be unpublished/delete. For the moment, it's better to have active, but in new JEM version should eliminate of rest of J3 & J4 because now they deprecated and with J6 will disappear.

Other thing to change is convert all JEM plugins to the new plugin structure..... first finder and after the others.

**Comment by mckillo** [comment]
Test JEM with commit above (more review migration J class).

**Comment by jojo12** [comment]
I tested a lot w/o compat plugin, replaced and tested again. Then I proposed my solutions in commits in 4.2.2-dev.
