### ISSUE TITLE
Invalid contact link when SEF is on

### ISSUE THREAD

**Issue by Heklaterriol** [jemproject/JEM-Project#1757]
I have created a contact “David” and entered it as a contact in an event.
However, the link on the JEM details page is **incorrect** and looks like this:
https://www.domain.tid/de/component/contact/contact/david?Itemid=102
Where 102 is the ID of the home page.

If I call up the contact from a list of contacts, I get the following **correct** link:
https://www.domain.tid/de/contacts/david

If I switch off “Search Engine Friendly URLs” in the Joomla configuration, it works.
Via the JEM detail page I get the following link:
https://www.domain.tid/index.php?option=com_contact&view=contact&id=2&Itemid=102&lang=de
Via the list of contacts:
https://www.domain.tid/index.php?option=com_contact&view=contact&id=2:david&catid=4&Itemid=345&lang=de
Both work.

**Comment by mckillo** [comment]
This happens because Joomla couldn't find any menu item for this URI when SEF is active.

Debugging:

The Joomla route for the contact extension requires the catid (category ID) to locate the contact and generate the correct URI.
The catid is the ID of the contact's category.

Solution (see new commit):
Add code to create a contact link that includes the catid of the contact.

Now, the new URI works correctly, and the contact link works in the event. Test it.

**Comment by Heklaterriol** [comment]
Perfect, it works!
