### ISSUE TITLE
New problem in J!5.1.1: Fehler: Unknown column 'a.state' in 'field list'

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1763]
I was creating a new event in backend. I got the error:

> danger
> Speichern fehlgeschlagen. Fehler: Unknown column 'a.state' in 'field list'

The Event was created, but with no starttime and endtime in backend create form, in frontend event detail the start and endtime is written. 
When I go from backend events to the chosen event, the start and endtime is visible. When I then click on save, I get the error and the start and endtime is away
EDIT:
I had to change the category: I was not able to save nor in backend, nor in frontend! With the same notification
EDIT 2:
In addition: the modules don't show the time!

**Comment by jojo12** [comment]
I assume, it has to do with calendar time

**Comment by mckillo** [comment]
I can't reproduce it with JL 5.1.1, PHP 8.2 and JEM-4.2.3-dev and I have tried several combination to create, edit and save events. Give me some more information (actions, step by step) or capture.

JEM only use state in two sites:
- in the #__jem_venues table, 
- in administrator\components\com_jem\models\forms\venue.xml file is right, in this xml file is defined state for venues.
Check two sites, because I think that one of them is wrong.

**Comment by jojo12** [comment]
WRONG ALERT: sorry.
after reupdating and testing: NO PROBLEMS
(my question: had it to do with my tests on jem_finder?)
can be closed
