### ISSUE TITLE
Warnung Incorrect version sequence. Cannot upgrade from 4.2.3 to 4.2.3-beta1.

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1815]
There is a problem with my sites, I worked on with the dev. I can't update.
Please find a solution, before releasing!
EDIT: 
Is update from earlier versions possible? 
from 4.2.2 it works, Rest I can't test

**Comment by mckillo** [comment]
That is normal, you can downgrade your JEMversion (manually). The update doesn't run if it's the same version (script).
Change the JEM version in the xml file and #__squemas (db) to 4.2.2.

**Comment by jojo12** [comment]
I don't understand. What is #_squemas?

**Comment by mckillo** [comment]
In the Joomla database, there is a `#__schemas` table (`#__` represents your database prefix). In this table, Joomla stores the version of the JEM database structure. Some entries in this table have `version_id = 4.2.3`. The other column, `extension_id`, is the ID of JEM in the `#__extensions` table. This value is `4.2.3` in our `JEM-4.2.3-dev` branch, and it represents the latest JEM SQL schema reference. If you want to apply the *.sql file from the zip, the schema version must be lower than the install version.

**Comment by mckillo** [comment]
This is only to simulate the upgrade installation, but the best approach is a true upgrade on a fresh Joomla installation.

**Comment by mckillo** [comment]
In the past, we saw that using letters in the number version can cause update issues. If we want to include letters, they should be in a fourth field and not mixed with the third field, which is meant for patch numbers.

**Comment by Heklaterriol** [comment]
As the current version is 4.2.2. I wanted to move to 4.2.3, but this does only work, wehn updating from a version lower than 4.2.3.
In our case with the testing of 4.2.3, it is not the case. Sorry for that. 
To test the update it is necessary to have JEM 4.2.2. installed.

**And because of this issue, I came across an other thingh:
I think that the correct version number is 4.3,** as we  also have new features.
See the discussion about version numbering here: https://www.joomlaeventmanager.net/kunena/jem-4-x-roadmap/12454-milestones-handling#30845

What do you think.

**Comment by mckillo** [comment]
I agree with jumping to 4.3.0, there are many new feaures, this release isn't a pacth.

**Comment by Heklaterriol** [comment]
see here: https://github.com/jemproject/JEM-Project/blob/JEM-4.2.3-dev/pkg_jem_4.3.0.b.zip

**Comment by jojo12** [comment]
the b is not a problem?

**Comment by Heklaterriol** [comment]
> the b is not a problem?

I tested to update from 4.2.3 to 4.3.0.b - OK
Then I tested to update from 4.3.0.b to 4.3.0 - OK
