### ISSUE TITLE
Translation files for some JEM plugins will be installed wrong e.g. JEM listevents...

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1854]
Translation files for some JEM plugins will not be installed e.g. JEM listevents...
Please control

**Comment by Heklaterriol** [comment]
I cannot reproduce this issue.
Not with a clen install ob JEM 4.3.1.b4 nor with and update from JEM 4.3.0. to 4.3.1.b4

**Comment by jojo12** [comment]
I think, this is not in b4. 
But in my livesites e.g. for jem list events, I found only english language files, no german,   don't know why.

**Comment by ernst67** [comment]
I think because the language files have moved.... or at least JEM is looking for a different url.

See my post here:
https://www.joomlaeventmanager.net/forum/jem-4-x-roadmap/12807-translations-for-jem-4-3#32102

For the translations... do I get rid of the language -referral? (de-DE)??
The question is outstanding for more than a week.

**Comment by jojo12** [comment]
(Can someone say me, why you don't read my comments (or here or in joomlaeventmanager.net?)
Some language files are installed on the wrong  places! So there is no translation!

**Comment by Heklaterriol** [comment]
OK, thank you. This is important.

Do I see it right, that the second occurrence of "and instead of" has a mistake
(<files folder="site_de-DE" target="plugins/**jem**/content/language/de-DE">)?

The whole should be:

instead of:
`<files folder="site_de-DE" target="plugins/jem/content/language/de-DE">`
should be:
`<files folder="site_de-DE" target="plugins/content/jem/language/de-DE">`

and instead of:
`<files folder="site_de-DE" target="plugins/jemlistevents/content/language/de-DE">`
should be:
`<files folder="site_de-DE" target="plugins/content/jemlistevents/language/de-DE">`

**Comment by jojo12** [comment]
> Do I see it right, that the second occurrence of "and instead of" has a mistake
()?
in the wrong xml-file it is really
<files folder="site_de-DE" target="plugins/jem/content/language/de-DE">

No, I think, the one who wrote this address, was thinking wrong.
it must be inside of "plugin/content" because it's a special plugin of content.
Because of that it must be:
`<files folder="site_de-DE" target="plugins/content/jemlistevents/language/de-DE">`

**Comment by jojo12** [comment]
ernst67 wrote he is changing it. Please speak together!

**Comment by Heklaterriol** [comment]
> Do I see it right, that the second occurrence of "and instead of" has a mistake

Waht I meant:
![code](https://github.com/user-attachments/assets/b02f38c5-26e7-446c-a3ca-5795b0421f51)

and

> No, I think, the one who wrote this address, was thinking wrong.
> it must be inside of "plugin/content" because it's a special plugin of content.

Yes, I got it

**Comment by Heklaterriol** [comment]
And this is something Ernst has to do, right?

**Comment by ernst67** [comment]
Yes, I'm working on it. But Jojo's edit of your post on the forum has confused me....

I now have:
```
		<files folder="site_en-GB" target="plugins/content/jem/language/en-GB">
				<filename>plg_content_jem.ini</filename>
				<filename>plg_content_jem.sys.ini</filename>
		</files>
		
		<files folder="site_en-GB" target="plugins/content/jemlistevents/language/en-GB">
				<filename>plg_content_jemlistevents.ini</filename>
				<filename>plg_content_jemlistevents.sys.ini</filename>
```

Please verify if this is correct and I'll send a new de-DE for testing to jojo

**Comment by jojo12** [comment]
I tested the new package german and it does what it should! Can be closed
