### ISSUE TITLE
J3 - Start date and end date Incrementally -1 day each on each save

### ISSUE THREAD

**Issue by neyworg** [jemproject/JEM-Project#772]
Testing on 3.3.1 both front end and back end.

If you save and close and re-enter your event your dates will be one less.

**Comment by Hoffi1** [comment]
Just to note:
On Joomla 3.3.6 I realised on com_finder (smart search) when typing in a date in Start Date or End Date filter fields this will be decremented each time I click on Search button.
This has nothings to do with JEM but is the same crazy effect.
If I add a time value behind that the date part is not decremented (but time part will be removed so day part will be decremented next time I click Search).

So it seems to be a "feature" of the date/time input field.

**Comment by JKoelman** [comment]
just to note:

when looking at libraries/joomla/form/fields/calendar.php it seems the values are formatted as Y-m-d H:i:s and as we're entering dates as Y-m-d it might give problems. beside of that it's also to fill in a filter (user_utc / server_utc) as we didn't fill in that one the default is being set and that's user_utc.

**Comment by Hoffi1** [comment]
Maybe it helps to set the filter to a unknown one, e.g. 'no_thank_you'. :wink: 
This will prevent any conversion and take the date as is.

But there seems to be a bug in calendar form / corresponding model because after converting it back and fore the result should be the same. (in my description for com_finder above browser posts a date to server where it could be converted to whatever and then the view creates the response where it must be converted from whatever back to it's original value - but I get one day before).

**Comment by Hoffi1** [comment]
As described in our forum (http://www.joomlaeventmanager.net/forum/jem-2-x-x-for-joomla-2-5-community-support/8842-date-advances-after-each-save) it seems to be a problem specific for timezones to the west of GMT/UTC. But it was on a time where both UTC and local time were on the same day. So it seems the time part is removed before conversion back from UTC to localtime (because UTC 00:00 is yesterday on local time).
Switching off the conversion is ok here because JEM 2 doesn't support timezones and stores date/time in db as typed in by user (which gives no problems as long as all users are in same timezone).

But together with com_finder it will give wrong search results because given Start date / End date will be converted from local time to UTC but we use local time. This can only be solved by implementing full timezone support - which I think will not be in JEM 2 but JEM 3.

**Comment by Hoffi1** [comment]
More details / how to test:
It's only required to change the timezone on backend
 Global Configuration -> Server -> Location Settings -> Server Time Zone.

Test East:
- Set timezone e.g. to Berlin, Save
- Show an event detail view and remember the date, click on Edit icon and...
  + date is correct
- Go to Finder (Smart Search) and choose a Start Date (in Advanced Search) and remember again
- click on Search and...
  + date is now date - 1 day.

Test West:
- Set timezone e.g. to New York, Save.
- Show an event detail view and remember the date, click on Edit icon and...
  + date shown in field is date above - 1 day.
- Go to Finder (Smart Search) and choose a Start Date (in Advanced Search) and remember again
- click on Search and...
  + date is correct

Test Zulu:
- Set timezone e.g. to Berlin, Save
- Show an event detail view and remember the date, click on Edit icon and...
  + date is correct
- Go to Finder (Smart Search) and choose a Start Date (in Advanced Search) and remember again
- click on Search and...
  + date is correct

**Comment by Hoffi1** [comment]
btw: If you have user profile plugin activated and user types in it's birth date (s)he will become one day older each time (s)he clicks Edit if the server stays e.g. in New York. :grinning:
