### ISSUE TITLE
import-view: add option to import el 1.1 automaticly

### ISSUE THREAD

**Issue by JKoelman** [jemproject/JEM-Project#864]

**Comment by JKoelman** [comment]
will take a look at this one

**Comment by JKoelman** [comment]
![clipboard01](https://cloud.githubusercontent.com/assets/2514855/7197617/404de36c-e4e3-11e4-9f14-efbdee545b05.jpg)

**Comment by Hoffi1** [comment]
Does it detect EL version also if only tables are there but EL isn't installed? (no entry in extensions table)
It should be possible to import EL tables from different db, maybe choose the different prefix, and then import with correct EL version assumed.

**Comment by JKoelman** [comment]
@Hoffi1  
it first checks for the catsid field and if found it assumes 1.0/1.0.2.
If not found it will check the settings-table for "ownedvenues" and if found it assumes it's 1.1x

maybe it's easier to have a "version" field, but well we already had that discussion some time ao.

**Comment by JKoelman** [comment]
the import will look at the current database but guess it can be tweaked to look at a different db.

**Comment by Hoffi1** [comment]
Thanks Bluefox. I think export/import db tables is easy enough. Admins not able to do this will also not be able to fill in all the data required by JEM to open the other db. :wink: 

btw: I'm a bit confused: 19:25 MESZ (means 2 hours 20 ago) I got the email with your screenshot (you posted 9:22 MESZ) and until now no emails about your last two posts. So I was surprised to see them yet.

**Comment by JKoelman** [comment]
adding this one will take a bit longer then expected..  there seems to be a problem with it so have to test a bit more.

**Comment by JKoelman** [comment]
did notice that the attachments function wasn't fired up, even if the option was chosen.

am thinking of adding a jem_import table to store detected versionnr and maybe it can be usefull in the future for other settings. on the other hand it can be that I'm thinking way to difficult so will give it a rest.

**Comment by Hoffi1** [comment]
I don't know which problem the table should solve so I don't have an opinion.
To remember things over multiple calls one can use user states which will be available within the current session. To remember persistant a db entry would be required.

**Comment by JKoelman** [comment]
the thing is that the $version variable was causing a problem.  

For example: we want to import 1.1x
- at the start of the import process we are retrieving a versionnr and it's stating "1.1.x" 
so far so good, but in step4 that variable is stating "1.0.2" 

ah well, will try a bit more to see what the problem is and would be nice if a table is not needed.

**Comment by Hoffi1** [comment]
Ah, understand. For me this sounds like user state - same as we remember e.g. filters of different list views.

**Comment by JKoelman** [comment]
was using ```$this->getState + $this->setState``` but doing so was not working so tried ```$app->setUserState("import.version",$version); + $app->getUserStateFromRequest + ``` and that seems to be working.

**Comment by Hoffi1** [comment]
I would like to have EL 1.1 support in JEM 2.1.4.

**Comment by JKoelman** [comment]
am using my phone now so can't read the comments you made that clear.

did indeed use code of JEM3 and tried to modify it for JEM2.  the tables were altered to give it the tablenames in use. think it was mentioned a while back in the forum or it was an issue at Github.

guess things should have been done better and did commit to soon.   so it's fine with me if you want to revert the changes.

**Comment by JKoelman** [comment]
ah well think it's the best for now if I revert the changes for now so will do that tomorrow morning.

**Comment by Hoffi1** [comment]
I implemented EL 1.1 support as good as possible.

At first I realised that EL 1.1 seems to work only on J! 1.5, I couldn't install it on a J! 2.5 site. So I setup a J! 1.5 site (on my old server because it doesn't work on PHP 5.5), installed EL 1.1 and filled some data. Then I exported the tables and tried to import.
All works fine if the user ensures some preconditions:
- User ids maybe different. That's a big problem. If an id doesn't exist current user's id is used. But on group members and attendees these records are skipped. More bad would be ids meaning a different real user. Meaning on old site Anne (with id 42) had registered but on new site Bob (with id 42) must attend!
The only way at the moment is to manually prepare the tables before starting the import.
- Access ids are different on J! 1.5 and e.g. J! 2.5. On J! 1.5 we have 0 = public, 1 = registered, 2 = special. On a default J! 2.5 site we have 1 = public, 2 = registered, 3 = special and an Admin which can change and enhance this. I added an option where user can tell Importer to increment access ids. Alternatively user must adapt the tables manually before importing.

I tried on a J! 2.5 site with different table sets from EL 1.0.2 and 1.1 and got what I expected. I hope someone can verify my expectations. :smile: 

I also added some longer texts hopefully giving enough hints for a successful import.
