### ISSUE TITLE
settings userrights: registration makes no effect

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#879]
see #16537 and following: this problem is in 2.1.1 too (I never tried other settings than optional, but it seems no and yes make no difference!

**Comment by Hoffi1** [comment]
@jojo12: What's the number 16537 for?

**Comment by Hoffi1** [comment]
...ah, it's a post id of our forum.

I also use "optional" - will take a look, thanks.

**Comment by Hoffi1** [comment]
Searching for this option name I only found files related to JEM settings itself.
So yes, it makes no effect.

Because it's a global setting I would suggest to change the options / their meaning:
- No: Registration completely disabled, event creator has no chance to change this.
- Yes (disabled by default): Registration possible but disabled by default, event creator can enable registration.
- Yes (enabled by default): Registration possible and enabled by default, event creator can disable registration.
So Yes / No gives event creator a permission whereas on Yes we provide the two possible decisions as default which will preset the field in editevent view on new events.

Not sure if a No makes sense on "Allow event registration cancellation".
Maybe instead we should have global setting "Allow event registration" Yes / No to completely switch on/off this feature globally. Below we could provide fields to give default values for "Registration", "Unregistration", "Max places", and "Enable waitinglist" which require a "Yes" above.
