### ISSUE TITLE
In mod_jem_banner: wrong method to add "Uhr" behind time

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#883]
Should be changed. I was trying to add a choice for the timename.
But perhaps we can take it from the extension itself.

**Comment by Hoffi1** [comment]
Hm... there are a lot more things to fix. I found duplicate language strings, offset not working etc. Seems the teaser module was a bad base point. :wink: 
Currently I walk/debug through the code and try to fix all...

**Comment by jojo12** [comment]
about line 163ff should be:
				/*wenn Datum angezeigt werden soll*/?>			
					<?php if ($item->time && $params->get('datemethod', 1) == 1) :?>
					<?php			
				/*es muss nur noch die Zeit angezeigt werden (da Datum auf Kalenderblatt schon angezeigt) */?>
						<div class="time">
						<?php $starttime2 .= JEMOutput::formattime($result->time);?>
						<?php echo $starttime2; ?>
						</div>
					<?php endif; ?>

**Comment by Hoffi1** [comment]
I would like to generally use JemOutput class to format date and time values.
Maybe we should add options for date format, time format, time suffix with fallback to component's settings. Also because you only show start date/time such an option maybe useful too in which case enddate/endtime will be suppressed.

The only thing I have no universal idea yet is for the "um" which should mutate to "von ... bis" in case of endtime should not be suppressed. - or you can live with default formatting as used by component without "um". :smile:

**Comment by jojo12** [comment]
I agree with using JEMOutput class.
and yes, I can live without "um"!
