### ISSUE TITLE
Acymailing plugin: COM_JEM_OPEN_DATE not translated

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#886]
Hi, in the Acymailing plugin I can choose events with open dates. But the term COM_JEM_OPEN_DATE is not translated in the newsletter. In which language file this has to be inserted?

The possibility to choose open dates is good: like that I can search for interested people!

**Comment by Hoffi1** [comment]
It's defined in component's language file which isn't loaded here.
I think the simplest way would be to add it to plugin's file too.
(normally I must suggest to load component's language file as clean solution - but this will parse a lot of lines with hundreds of strings we only need one from ...principles can be sooo hard...)

**Comment by Hoffi1** [comment]
Also ```open date``` shouldn't be shown as ```today``` in popup, of course.

**Comment by jojo12** [comment]
you're right: I forgot to look in the settings: I choosed show past. Past events are hidden, when I use hide past events.
The open dates are only visible, when show past events is choosen.

**Comment by Hoffi1** [comment]
Ok, so just to remind me I have to
- ensure Open date is always shown as Open date (not today)
- ensure COM_JEM_OPEN_DATE will be translated
- convince the plugin that open date is always in the future :wink: 
- allow open date events to be selected manually but not included in auto-lists (or add tag param to let the author decide)

**Comment by Hoffi1** [comment]
Status update (locally working but not committed yet):
- Open date is handled consistent and always shown as "Open date"
- Because some classes of JEM component are included/used which may use other language strings too I decided to load component's language file (means: I changed my opinion to follow my hard principles :wink: , means also: no changes on any language files required)
- I added code to allow decision of Show open date events = { No | Yes, also | Yes, only } for auto-created lists - the tag param works fine, the corresponding option in the popup (which creates the tag) is missing yet.
- I changed/swapped the date/time format: in popup's table short format is more handy but in the mailing itself there is enough space for the long format (as defined in component). Maybe the plugin could become it's own params for the three well-known format strings (with fallback to component's formats) - but that's not on my current focus, but fine for discussion. :smile:

**Comment by jojo12** [comment]
sound good :-)

**Comment by Hoffi1** [comment]
(please note: commit not tested on Joomla 3.x yet)

**Comment by jojo12** [comment]
I tested on Joomla 3.3.6 with JEM 2.1.1: didn't work
the modal window for choose opens, but is blank-white, the only visible thing is: Schlagworte

**Comment by Hoffi1** [comment]
Thanks Jojo. I already planned to setup a J! 3.3. site with all components we support (Acy, CB, JComments). Then I can test/debug the plugin and finally increment it's version to 2.1.
Too bad you can't test the functionallity yet. I would like to get your feedback. :smile:

**Comment by jojo12** [comment]
with error notices develop I get:
Parse error: syntax error, unexpected end of file, expecting function (T_FUNCTION) in /srv/www/vhosts/mysite.ch/httpdocs/plugins/acymailing/tagjem/tagjem.php on line 684

**Comment by jojo12** [comment]
did find, my problem, the end was not copied. will try again!

**Comment by jojo12** [comment]
exchanged the xml too, but now I get:
500 Fehler beim Laden der Formulardatei

**Comment by jojo12** [comment]
when I use the old xml file, i see in the modal window all events even open dates.
And it's now written open date.
And in the newsletter is open date too.
works fine. 
will look what's wrong in the xml.

**Comment by jojo12** [comment]
super: all the opendates only in the newsletter!
