### ISSUE TITLE
mod_jem_banner/mod_jem_teaser: open date

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#889]
experiencing: if a chosen event (eventID) has open date, the module isn't visible.

Loud thinking: That's a pity. If the module would show this event, it could be good for regular repeted events. (In our parish is each thursday a prayer for young people) But it doesn't make sense to show this so much in the simplelist. 
If module is visible, then I can write in the description or in the title "every thursday".

**Comment by jojo12** [comment]
this seems very difficult. Better to leave it now.

**Comment by Hoffi1** [comment]
On teaser module events with open date are allowed now IF event id(s) are specified.
This is because open date is interpreted as 0 so such events will always be shown first - in most cases not what user expects I think.
But if user explicitely want to see specific events they should be shown also if open date.
Alternatively the well known Open date combobox could be added to let user decide between No, Yes also, Yes only - not sure if this is required or more confusing.

**Comment by jojo12** [comment]
Yeah, you're excellent. I thought, that will be a problem. But it seems yout thought on all these things.

**Comment by Hoffi1** [comment]
I try my best. :smile:

**Comment by Hoffi1** [comment]
In banner module too. Also a bit improved, e.g. shows always "Open date" independent of date mode (we don't need all the calculations if result is already clear :wink: ).
