### ISSUE TITLE
JEM 2.1.not ready for Joomla 3.4

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#892]
Hi, I tried to install JEM 2.1.(2) on Joomla 3.4 RC.
But there's a limitation, which says: you cannot install on this Joomla version.
Because Joomla 3.4 stable will be here in about one week, it would be good, you adjust the package, that it will be possible to install it there too!

**Comment by Hoffi1** [comment]
Ahh...thanks Jojo. :+1: 

Think that's only a problem of the restrictive version check in component's script.php(197).

But of course, it's completely untested on J! 3.4 yet so it's not completely wrong. :grinning:

**Comment by jojo12** [comment]
I would like to test in jomla 3.4 rc

**Comment by jojo12** [comment]
When I try to install the package: I get the error
JLIB_INSTALLER_ABORT_INSTALL_CUSTOM_INSTALL_FAILURE 
even when I added the 3.4 or disabled the joomla pass

I then unzipped the JEM 2.1.2 package and tried to install each extension separately.
all modules and plugis are installed with no problems
only com_jem brings an error:
JLIB_INSTALLER_ABORT_INSTALL_CUSTOM_INSTALL_FAILURE

**Comment by Hoffi1** [comment]
Yes, because there the line to allow 3.4 must be added, not to pkg_script.php.

I installed J! 3.4 RC2 now and tried installation. After fixing script.php all worked fine.

**Comment by Hoffi1** [comment]
Not fully fixed.
There is real problem caused by J! 3.4 which gives 404 in popups choosevenue/choosecontact on frontend.

**Comment by jojo12** [comment]
on my updated to joomla3.4stable and JEM 2.1.2 I can't reproduce this! Can choose in frontend contact and venue without any problems!

**Comment by Hoffi1** [comment]
I would love to confirm this. :smile: 
I need a 3.4 stable site, have only RC2 yet.
So I keep it unsolved until it's clarified and hopefully understood...

**Comment by Hoffi1** [comment]
Setup a fresh site with J! 3.4.0 and installed JEM 2.1.2 (+ installer fix).

On both choosevenue and choosecontact I get an error.
After debugging I found admin - site confusion, finally the ```addfieldpath="administrator...``` in models/forms/event.xml causes the problems because both site and admin contain modal fields for contact and venue.
As solution these lines must be removed (also in venue.xml) to get the correct fields.
Only for event.xml/details it's required for countryoptions field (or this file must be copied to frontend part).

Also there are some problems with catoptions field I will track in a separate issue...
