### ISSUE TITLE
JEM 2.0.2: mod_jem_cal: tooltips problem

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#896]
I newly seen that (this was earlier resolved!)
tooltips should be otherwise!
![modcal](https://cloud.githubusercontent.com/assets/2960236/6354823/3eb82152-bc52-11e4-9601-96bea97afe9c.png)

**Comment by Hoffi1** [comment]
Please update to JEM 2.1.2, version 2.0.2 is outdated and no longer supported. :laughing: 

But really: On my test sites it works perfect - on J! 2.5 as well as J! 3.3.6. Is there any JavaScript problem? Have you tried a standard template?

**Comment by JKoelman** [comment]
or the tooltip is not being loaded or something like that.

**Comment by Hoffi1** [comment]
In mod_jem_cal.php the tooltip behavior is loaded. I also tried with homepage where the component stuff isn't loaded to exclude such things - looks all fine. Also I disabled the jQuery Easy plugin I normally use - no problem. Also I tried Protostar - no problem too.
So I have no further ideas yet...

**Comment by jojo12** [comment]
I don't know what this was. There's not any more a problem. I updated now after backup to Joomla 3.4 stable. No problem until now!

**Comment by JKoelman** [comment]
to note:

in case of Joomla 2.5.x it could have been due to a miscommunication between the template and the class in the module like mentioned here: http://www.joomlaeventmanager.net/forum/jem-2-x-x-for-joomla-2-5-community-support/8914-calender-events

the calendar-module is having a class "hasTooltip"  but the template was checking for "hasTip"

**Comment by Hoffi1** [comment]
In case of Joomla 2.5 the class "hasTip" will be used by JHtml::tooltip() as default because there "hasTooltip" is unknown.

On my J! 2.5 site JEM 2.1.2 shows me the good old "hasTip" tooltips while on my J! 3.3 site the new "hasTooltip" tips are shown.

Do you have a J! 2.5 site disproving my theory? Then let me know please.
