### ISSUE TITLE
mod_jem_teaser: show date doesn't show time

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#904]
hi, I've just seen in your changes: when choosing show daydifference, it's ok, but when show date.
the time icon and the time itself is not visible
I get the time icon with padding-top: 20px.
But the time is not there!

**Comment by Hoffi1** [comment]
Thanks Jojo, will take a look. Hadn't checked it tonight because I only fixed some little real bugs - that was the mistake...

**Comment by Hoffi1** [comment]
Because my time-related changes are ignored (assigned to $dummy) This must be an older bug.
If I look at tmpl/default.php it seems there is something in ```$item->time``` but ```JEMOutput::formattime()``` makes it to nothings. This can be if it's not accepted as valid time value or if there is no format set in JEM Settings.

Could you remove ```JEMOutput::formattime``` in mod_jem_teaser/tmpl/default.php line 85 so it will directly ```echo $item->time;```.

Think it was inteded to handle the addSuffix thing, but it's the wrong way so I will change it (by using your addSuffix calculation from banner mod which is the best way possible).
