### ISSUE TITLE
global setting for first day of week seems not to work!

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#917]
see #17766 in forum:
@Hoffi: Until know I thought the settings in global configurations is a preset for  new menues. But this seems not to work.
I can choose there sunday, and get monday in the calendar.
Only when I choose sunday in menu settings, I get sunday.
can you reproduce?

**Comment by Hoffi1** [comment]
Will take a look.

With "preset" I think it's difficult because menu items are handled by Joomla itself. That's why often an option "use global setting" exists which causes exactly what you mentioned. In calendars only Sunday or Monday can be choosen where the default selection must be hard-coded in xml file..

**Comment by JKoelman** [comment]
did take a peak to (JEM3) and there that setting in the back is not being used so it's going to be removed.
