### ISSUE TITLE
mod_teaser and mod_banner: calendar page colour?

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#929]
Hi, I don't know if this is normal or buggy?
when I have more than one of these modules on one page,then the calendar page colour is always the same (the colour of the first module in that page). You only can change it, changing in this first module.

Different colours on the same page are not possible.

**Comment by Hoffi1** [comment]
Hm... this shouldn't be.

Argh... that's by design. :cry:
The params are on a per-module-base but then we load a $color.".css" defining styles for the same css classes different.

The solution would be to add the color to the classname too. (keeping the separate files for each color is ok, maybe sometimes we like to add "custom" colors :wink: )
