### ISSUE TITLE
is it possible to integrate "guest"-events in JEM 2?

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#940]
in JEM 3 settings there is the possibility that guest can enter new events too. Can this be integrated in JEM 2 too?

**Comment by Hoffi1** [comment]
As somewhere else already discussed I'm not a friend of opening this door.
It will require a lot of work to prevent e.g. spam, ensure email authenticity etc. which I would like to let "expert" components do.
As it is normal to register before you can post on a forum it should be also normal to register before you can post an event.

**Comment by jojo12** [comment]
Ok, you're right, even whenit would be practic sometimes.
Can be closed.

**Comment by ernst67** [comment]
Sorry to reopen this issue.... but i'd like to ask an additional question:

Could it be implemented with automated publishing automatically set to "NO"?

**Comment by jojo12** [comment]
Thank you for that question

**Comment by JKoelman** [comment]
@Ernst67 would say no, this as the things Hoffi mentioned are still things that should be taken into account.

**Comment by Hoffi1** [comment]
Ok guys, some more details describing my "not a friend of":
- JEM requires a valid user id to get at least the name in nearly all db queries. Because a guest has no id they must be changed.
- The site owner must validate the submission and so at least a valid email address of the author is very helpful. This information must be requested by edit view and stored somewhere.
- As described above email address must be checked but also the view must be protected against spam or DoS bots. It makes no difference if the events will be published or not if a bot net floods the server with tons of event submissions.
- As sayed the guest should provide an email address and any name he like. To register a guest must provide an email address and choose a name he like (ok, and a password he should also remember). The requirements for the guest are (except the password) the same in both cases but the second way is completely implemented and can be used. So why should we invest a lot of time to implement a second way to reach the same goal?

**Comment by jojo12** [comment]
How is it with our jcomment plugin? With that it' s possible too enter comments without identification!

**Comment by Hoffi1** [comment]
On JComments we talk about simply comments. Readers can like or dislike them.
On JEM we talk about events where users would like to attend by driving long distances or may have other real costs. So the authenticity is much more important.

**Comment by jojo12** [comment]
Ok. But events from guests can be directed in a special category, you can categorise as not sure.

**Comment by Hoffi1** [comment]
Hey, you can try to find thousands more workarounds - I'm not willing to invest hundreds of hours for a useless feature making the code much more complicated and unreadable, sorry.
The cost - effort relation is completely unbalanced.

**Comment by ernst67** [comment]
My idea was to set them as non-published by default.

The concept would be for any event-website to make the barrier of submitting a new event as low as possible. But I do understand Hoffi's remarks, and indeed; this way we would allow to write new events to the database (in and unpublished state), thus allowing bots to lay a heavy traffic to the site.

Hmm... maybe not as easy as 1,2,3 after all. Guess it's not so easy as projected

**Comment by jojo12** [comment]
@all: after sleeping with thinking, I really can accept the decision, not to integrate guest events into JEM. This will be the big difference between 2 and 3.
Safety is more important!
Sorry, I have started this discussion. But I can accept now much more your principles, Hoffi.

**Comment by ernst67** [comment]
Fully agree as well. Let's close the issue.

**Comment by Hoffi1** [comment]
Thanks and please sorry for my bugged emotions.

**Comment by ernst67** [comment]
Not at all. Thanks for the concise explanation!
