### ISSUE TITLE
Ical-export doesn't take the max limit into account

### ISSUE THREAD

**Issue by JKoelman** [jemproject/JEM-Project#955]
In the backend it's possible to set an option for max ical items.
But this setting is not working as Avalon did report over here: http://www.joomlaeventmanager.net/forum/jem-3-0-x-for-joomla-3-test-forum/9135-jem3-ical-export-problems?start=6#18885

**Comment by Hoffi1** [comment]
Yes, it's caused by a conflict in model state 'limit' vs. 'list.limit'.
But the fix is more tricky because list.limit is also remembered in user session and user would be surprised to see next time requesting a list view only e.g. three items per page (whereas e.g. 15 is shown in dropdown box top right).

Related views: category, eventslist, venue
Maybe same problem on feed format, so day view could be involved too.

**Comment by JKoelman** [comment]
had a typo with the issuenr but did change some files and should be working.

in the populateState functions we are defining a limit/start but it should only be used in case of tables. So to bypass that we can check for the format (raw). If that's the case it won't define the limit/start again but will take the defined values from the raw file.
