### ISSUE TITLE
possible bug: creating new event as publisher

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#970]
my publisher creates a new event in a category which is "special".
He sees the category in editeventview
he can enter the new event
he sees the event in eventlist.
in administrator I see that the event is "public".

I tested more as author, editor:

I think it's not yet resolved who can see in editevent view the categories.
Also categories have rights!

**Comment by Hoffi1** [comment]
Hi @jojo12 
What's the problem?
- All users "more" than Registered (Author, Editor, Publisher, Admin...) are allowed to see View level "special" (by Joomla default).
- New events get the site's default view level (Global Configuration - Site - Default Access Level) as long as creator doesn't change it. It is not changed on Save depending on category attached because we support multiple categories (also it would confuse the user because on Save is too late).
- In Editevent view all categories are listed user is allowed to see. With Joomla default installation only guests and registered users are restricted. So you should create own View levels (e.g. "Admins only") and assign them to Super Users and Administrators only to see categories on this View level hidden for Editors, Publishers etc.
- If you than have a "public" event attached only to an "Admins only" category (so it was created by an Admin, yes) e.g. your Publisher will NOT see this event because view level of event AND at least one of the categories must match - that's my expectation.

**Comment by jojo12** [comment]
oops: I learned at new something about ACL. Thanks. So this works as wanted.
This issue can be closed.
