### ISSUE TITLE
backend Categories view: indicate invalid group ids

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#972]
I show you the categories in administrator and
the createeventview as publisher with settings "all registrated"
the createeventview as registrated with settings "all registrated"

loud thinking: this seems not to be an import problem? but what ?
in dev 6
EDIT: took away the image

**Comment by Hoffi1** [comment]
Hi @jojo12,
I don't trust what backend shows us because it makes no sense.
Could you please take a look directly on DB table ..._jem_categories if on a not shown category (e.g. Reli-EF) access is 1 and groupid 0 ? My suspicion: there's a groupid of a non-existent jem group.

On own test I set an invalid groupid (directly in DB). In createevent view this category was no longer listed but on backend a hyphen was shown on Group column - same you see.
If you can confirm this as the cause we should rename this issue as
"backend Categories view: indicate invalid group ids" or so.

**Comment by jojo12** [comment]
@Hoffi1 
I think you're right:
in the exported from site I had a group "Mitarbeiter".
this group wasn't in the imported to site.
the visible categories have 
published=1, access=1, groupid=0
the others have published=1, access=1, groupid=1
I created now the group "Mitarbeiter", in administrator you see, that this group is associated with the categories with groupid=1.
the categories in createeventview are the same with the ? included.
So we can recall the issue

**Comment by jojo12** [comment]
I've just seen, this seems to be in JEM 2.1.4.2 too!

**Comment by jojo12** [comment]
I associated the 3 categories with the group "Mitarbeiter".
In create event view they were away, that's ok.

Then I changed the associated group to "no group".
The problem in create event view was back.

Loud thinking: Is it possible to release a category from his associated group?
it seems not

**Comment by jojo12** [comment]
no, se image:
![catreg2](https://cloud.githubusercontent.com/assets/2960236/9698938/c69041d2-53cd-11e5-8c92-e4038d3641fa.png)

**Comment by Hoffi1** [comment]
Ah, you mean the question mark? That's a feature! :wink: 
Normally categories are shown as "graphical" tree indicating sub categories.
In case of Firmpraktika there is a parent category but it's "secret". So all sub categories without visible parent are moved to the end of the list and prepended by a question mark to indicate that orphaned state.

**Comment by jojo12** [comment]
aah, well, I didn't know.

**Comment by jojo12** [comment]
I tried your fix, with import of categories with associated group(s?) Works fine. Thanks a lot
