### ISSUE TITLE
dev8: how can a publisher edit/publish a venue?

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#980]
Hi, I installed dev8 from today. installation ok
With author I created a venue. ok. Venue is unpublished, this is ok.
I tried with publisher to open venue in frontend. this seems only be possible with venues menu.
But I can't edit/publish it.
-->this seems to be a bug.

(loud thinking:
perhaps we need a same system with icons published/unpublished
it should somewhere be visible that it exists, but not published.)

**Comment by Hoffi1** [comment]
How is your publisher configured?
Normally a Publisher is also an Editor so he can publish by editing the venue.
But if you have a pure publisher ("edit.state" permission only) he can't publish a venue, event - but also no article.

I share your minds but it's not so easy to implement. Currently you can (un)publish in the two edit views or the my events / my venues views which is not good for publishers (as long as they are not also editors which can use the edit views).
For events we could enhance the simplelist by showing check and status column (configurable). But for venues we don't have a list view (except My Venues). Instead we have a blog view which would require a different way.
Another idea would be to add (un)publish button on top right area of details views. But this also requires enhancement of controllers and models to allow these actions - possible but takes a bit more time...

**Comment by jojo12** [comment]
thanks.
first of all: I found the way to publish authors venue
all my joomla user rights are unchanged.

(I have to go to venues view, then the venue is visible (difficult to find, if you have a lot of venues)
I have to click it for details, then I see the edit icon and can edit and publish it.)

one strange thing:
=> I try to edit event or venue as author (strange: it's possible, even if the JEM rights are: edit own events = no)
 that means: Joomla author is allowed to edit his own, even when JEM says no! Is this right?

your answers for my loud thinking: forget it, we can let this.

**Comment by Hoffi1** [comment]
> Joomla author is allowed to edit his own, even when JEM says no! Is this right?

That's correct. JEM doesn't say "I forbid", JEM only says "I don't allow". Your children know this principle: If you say "No" they ask mom. :wink: 

Generally, if an author is allowed to add stuff and edit own stuff globally on the site that's also allowed for JEM stuff. The only way would be to explicitely forbid this on JEM (via JEM Dashboard - Options where you configure Joomla ACL for JEM). Normally "forbid" on Joomla ACL takes always precendence so it shouldn't be used if possible. Better to create a new user group and don't allow.
Also because I can't differentiate between "not allowed" and "forbidden" on Joomla ACL I fear setting JEM right edit own events to Yes would allow users to edit own events.
So generally I would like to remove all these redundant AC settings and let admins use Joomla ACLs instead. The only gap yet: There is no way to configure permissions for events and venues different.
(also permissions on category level are not implemented yet so we can't remove JEM groups yet)

**Comment by jojo12** [comment]
Thanks,
I didn't try, but what's when a joomla publisher is allowed to publish/edit/create contents but not events.
Is it possible to make differences?

**Comment by Hoffi1** [comment]
Depends. If you really mean "contents" this publisher shouldn't have permission to modify events (look at JEM Options). But if the publisher has general permission (as Joomla's default Publisher has) it's also true for events and venues.

**Comment by jojo12** [comment]
So I would say, if it is possible that both system can exist in the same Jem, I would let it like that and not eliminate the Jem one. 
How it is with the mail plugin?

**Comment by jojo12** [comment]
sorry, I was a few days away. Back on my good old Desktop I looked into mail plugin: There seems no problem with infomails.

**Comment by Hoffi1** [comment]
Oh, I missed the time to ask what you meant with mailer plugin.
But generally the "I would like to remove..." was a vision, not a plan for 2.1.5. :wink: 
I know JEM groups are also good to add mailer recipients. So if JEM groups will be removed an alternate mechanism is required. (category's text field to add email adresses is no alternative - too limited and not handy)

btw: The mailer doesn't work on all my PHP versions integrated in Apache via CGI. (you remember, I need this to test JEM on PHP 5.3, 5.4, 5.6, ...)

**Comment by jojo12** [comment]
can be closed
