### ISSUE TITLE
Attendees Notification for event creator with mailer plugin

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#982]
is there a possibility to send attendees notifications to the event creator?
If not it's the administrator who does send such informations manually to the event creator.

**Comment by Hoffi1** [comment]
You're right, it would be useful to inform event creator.

Because we have optional Contact and creator I would suggest to add one option "Contact or creator" which sends email to given Contact or to creator as fallback. What do you think?

**Comment by jojo12** [comment]
good question! because in mailer plugin is only mentioned the creator, it was for me clear only to inform him, because normally he is responsible for his event. And we have the possibility, that he can see a list of participants in myevents. Perhaps this is easier.

So I don't know, if mail to contact.

**Comment by Hoffi1** [comment]
Ah yes, two points @jojo12. I thought the explicitely given Contact maybe the person to answer questions regarding the event. But you're right, the creator is the only one which can see the attendee list (in frontend). And yes, it's easier to implement.
Ok, let's simply inform the Creator. :+1:

**Comment by Hoffi1** [comment]
I reworked the mailer plugin a lot.
Attendees will be informed if event or connected venue changes, but not if the event has at least one hour finished. Also creators will be informed about attendees, changes or in case of event connected venue modifications. Nearly every group of recipients can be configured to become informed on all actions.

Also the mailings itself have changed. I added date/time etc. because e.g. on recurring events the title says nothings about the concrete event. On the other hand I reduced the templates. So there is one template for the user itself, and only one other template for all the other different recipients. This allows to send only one email to "multi-talents", e.g. creator, attendee and admin as single person. Now (s)he gets one email with the final sentence why (s)he got this mail. (I'm sure @jojo12 our great tester will love it! :smile: )
more precise: The actor always gets a dedicated email. Meaning e.g. an admin clicking on Register gets one email as actor (new attendee) and a second as admin, event creator, group member, ...

On back side this requires a lot of translation work... (after merged to master so transifex "see" it)

**Comment by jojo12** [comment]
yeah, this final sentence is a big help to test (and more) ;-)

**Comment by jojo12** [comment]
2 little questions:
in the language file there are some expressions with a ; before. Are they unused?

there are near identical expressions e.g.
PLG_JEM_MAILER_ADMIN_REG_WAITING_BODY_4
PLG_JEM_MAILER_ADMIN_REG_WAITING_BODY_8, -->which seems newer

can the old one be deleted?

**Comment by Hoffi1** [comment]
(a) Yes, they are no longer used and will be removed next time.
(b) The second version (with 4 more params) replaces the first version. I don't know how transifex works but my intention was to allow translators to copy old text to new define and adapt. That's why I not removed the old text defines.

**Comment by jojo12** [comment]
thanks.
all seems to work fine!

we had in the forum some other discussions: 
a) send email for new events for all joomla users. (I am against, or only if there's a possibility for a users to negate this.

b) send a notice for a new event only three days before event. ( I would say there something like selfcompetence of the users. I am against that.)

@all: what do you think?

**Comment by Hoffi1** [comment]
Thanks @jojo12 

regarding a) Use AcyMailing we provide a nice plugin for. :grinning: 

regarding b) That's a complete new feature. Maybe realisable with dedicated plugin?
One technical problem: Someone must enter the site to awake the mailer.
